// MathMaker v2 — original pixel-art sprites, authored as character maps.
// Each sprite is 16x16 (unless noted); chars map to colors, '.' = transparent.
// Rendered once to offscreen canvases and cached per (sprite, palette, scale).
var MM = globalThis.MM = globalThis.MM || {};
(function () {
  'use strict';

  const S = MM.sprites = {};

  // ---------- sprite definitions ----------
  // colors: char -> hex. Palette swaps override these per monster variant.
  S.DEFS = {

    // ===== terrain =====
    grass: {
      colors: { G: '#4e9e52', g: '#3f8746', L: '#63b167' },
      map: [
        'GGGGGGGGGGGGGGGG',
        'GGGGgGGGGGGGLGGG',
        'GGGGGGGGGGGGGGGG',
        'GLGGGGGGgGGGGGGG',
        'GGGGGGGGGGGGGGgG',
        'GGGGGGGGGGGGGGGG',
        'GGgGGGGGGGGLGGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGGGLGGGGGGGGG',
        'GGGGGGGGGGGGGgGG',
        'GgGGGGGGGGGGGGGG',
        'GGGGGGGGgGGGGGGG',
        'GGGGLGGGGGGGGGGG',
        'GGGGGGGGGGGGLGGG',
        'GGGGGGgGGGGGGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    grass2: {
      colors: { G: '#4a9a4e', g: '#3f8746', L: '#63b167' },
      map: [
        'GGGGGGGGGGGGGGGG',
        'GGGGGGGGgGGGGGGG',
        'GGLGGGGGGGGGGGGG',
        'GGGGGGGGGGGGgGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGGgGGGGLGGGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGLG',
        'GgGGGGGGGGGGGGGG',
        'GGGGGGGGLGGGGGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGgGGGGGGGgGGG',
        'GGGGGGGGGGGGGGGG',
        'GLGGGGGGGGGGGGGG',
        'GGGGGGGGGgGGGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    tree: {
      colors: { G: '#4e9e52', g: '#3f8746', T: '#2c6b34', t: '#3d8544', d: '#1f4f26', B: '#6b4a2f', b: '#52381f' },
      map: [
        'GGGGGttTTtGGGGGG',
        'GGGtTTTTTTTtGGGG',
        'GGtTTtTTTTTTtGGG',
        'GtTTTTTTtTTTTtGG',
        'GtTTtTTTTTTdTtGG',
        'tTTTTTTtTTTTTTtG',
        'tTTdTTTTTTtTTTtG',
        'tTTTTTtTTTTTdTtG',
        'GtTTTTTTdTTTTtGG',
        'GGtdTTTTTTTtTGGG',
        'GGGtTTdTTTtTtGGG',
        'GGGGGtBBbtGGGGGG',
        'GGGGGGBBbGGGGGGG',
        'GGGGGGBBbGGGGGGG',
        'GGGGgGBBbGGgGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    water: {
      colors: { W: '#2f6fc4', w: '#5d97e0', d: '#255a9e' },
      map: [
        'WWWWWWWWWWWWWWWW',
        'WWwwWWWWWWWWWWWW',
        'WWWWWWWWWwwwWWWW',
        'WWWWWWWWWWWWWWWW',
        'WdWWWWWWWWWWWWdW',
        'WWWWWwwWWWWWWWWW',
        'WWWWWWWWWWWWWWWW',
        'WWWWWWWWWWwwWWWW',
        'WwwWWWWWWWWWWWWW',
        'WWWWWWWdWWWWWWWW',
        'WWWWWWWWWWWWWwwW',
        'WWWWwwWWWWWWWWWW',
        'WWWWWWWWWWWWWWWW',
        'WWWWWWWWWwWWWWWW',
        'WWdWWWWWWWWWWWWW',
        'WWWWWWWWWWWWWWWW',
      ],
    },
    water2: {
      colors: { W: '#2f6fc4', w: '#5d97e0', d: '#255a9e' },
      map: [
        'WWWWWWWWWWWWWWWW',
        'WWWWWWWWWwwWWWWW',
        'WWwwWWWWWWWWWWWW',
        'WWWWWWWWWWWWWWWW',
        'WWWWWWWWWWWWWdWW',
        'WWWWWWWwwWWWWWWW',
        'WdWWWWWWWWWWWWWW',
        'WWWWWWWWWWWWwwWW',
        'WWWWwwWWWWWWWWWW',
        'WWWWWWWWWdWWWWWW',
        'WwwWWWWWWWWWWWWW',
        'WWWWWWwwWWWWWWWW',
        'WWWWWWWWWWWWWWWW',
        'WWWwWWWWWWWwWWWW',
        'WWWWWWWWdWWWWWWW',
        'WWWWWWWWWWWWWWWW',
      ],
    },
    mountain: {
      colors: { G: '#4e9e52', M: '#8a8578', m: '#5f5b50', S: '#eceade', k: '#3e3b33' },
      map: [
        'GGGGGGGSGGGGGGGG',
        'GGGGGGSSSGGGGGGG',
        'GGGGGSSSSMGGGGGG',
        'GGGGGSMMMMmGGGGG',
        'GGGGMMMMMMmmGGGG',
        'GGGMMMmMMMMmmGGG',
        'GGGMMMMMMmMMmGGG',
        'GGMMMmMMMMMMmmGG',
        'GGMMMMMMmMMMMmGG',
        'GMMMmMMMMMMMmmmG',
        'GMMMMMMMMmMMMMmG',
        'MMMmMMMmMMMMmmmm',
        'MMMMMMMMMMMmMMmm',
        'kMkkMMkMMkkMMkkm',
        'GkGGkkGkkGGkkGGk',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    wall: {
      colors: { K: '#4a4258', k: '#332c44', h: '#5c5470' },
      map: [
        'KKKKKKKkKKKKKKKK',
        'KhKKKKKkKKKKhKKK',
        'KKKKKKKkKKKKKKKK',
        'kkkkkkkkkkkkkkkk',
        'KKKkKKKKKKKkKKKK',
        'KKKkKKhKKKKkKKKK',
        'KKKkKKKKKKKkKKKK',
        'kkkkkkkkkkkkkkkk',
        'KKKKKKKkKKKKKKKK',
        'KhKKKKKkKKKKKhKK',
        'KKKKKKKkKKKKKKKK',
        'kkkkkkkkkkkkkkkk',
        'KKKkKKKKKKKkKKKK',
        'KKKkKKKKhKKkKKKK',
        'KKKkKKKKKKKkKKKK',
        'kkkkkkkkkkkkkkkk',
      ],
    },
    floor: {
      colors: { F: '#57506a', f: '#4a445c', d: '#3f394f' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFfFFFFFFFFFFF',
        'FFFFFFFFFFFdFFFF',
        'FFFFFFFFFFFFFFFF',
        'FdFFFFFfFFFFFFFF',
        'FFFFFFFFFFFFFFfF',
        'FFFFFFFFFFFFFFFF',
        'FFFfFFFFFFdFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFFFFFdFFFFFFfFF',
        'FfFFFFFFFFFFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFFFFFFFfFFFFdFF',
        'FFdFFFFFFFFFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFFFFfFFFFFFFFFF',
      ],
    },
    doorMagic: {
      colors: { K: '#4a4258', k: '#332c44', D: '#6b4fc0', d: '#523a99', Y: '#ffd94a', h: '#8d75d8' },
      map: [
        'KKKKKKKKKKKKKKKK',
        'KKKKkkkkkkkkKKKK',
        'KKKkDDDDDDDDkKKK',
        'KKkDDhDDDDhDDkKK',
        'KKkDDDDDDDDDDkKK',
        'KKkDDDYYYYDDDkKK',
        'KKkDDYYddYYDDkKK',
        'KKkDDYdDDdYDDkKK',
        'KKkDDYYddYYDDkKK',
        'KKkDDDYYYYDDDkKK',
        'KKkDDDDDDDDDDkKK',
        'KKkDDhDDDDhDDkKK',
        'KKkDDDDDDDDDDkKK',
        'KKkDDDDDDDDDDkKK',
        'KKkDDDDDDDDDDkKK',
        'kkkkkkkkkkkkkkkk',
      ],
    },
    chest: {
      colors: { F: '#57506a', f: '#4a445c', C: '#b0763e', c: '#8a5a2c', k: '#5f3d1c', Y: '#ffd94a', y: '#d8a03c' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFFkkkkkkkkkkFFF',
        'FFkCCCCCCCCCCkFF',
        'FkCCcCCCCCCcCCkF',
        'FkCCCCYYYYCCCCkF',
        'FkkkkkkkkkkkkkkF',
        'FkCCCCYyyYCCCCkF',
        'FkCCCCyYYyCCCCkF',
        'FkCcCCYyyYCCcCkF',
        'FkCCCCCCCCCCCCkF',
        'FkCcCCCCCCCcCCkF',
        'FFkkkkkkkkkkkkFF',
        'FFFFFFFFFFFFFFFF',
        'FFFFfFFFFFFfFFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    // Playtest round 4: the Mimic — a chest with the lid caught mid-grin.
    // Same wood/trim palette as the real chest (it studied), plus a dark
    // mouth, white teeth, glowing eyes, and a little pink tongue.
    // Transparent background: it's a MONSTER sprite (battle + bestiary),
    // not a tile — the world keeps drawing the ordinary chest tile for it.
    mimic: {
      colors: { k: '#5f3d1c', C: '#b0763e', c: '#8a5a2c', Y: '#ffd94a', y: '#d8a03c', W: '#fffcf0', d: '#2a1626', E: '#ffe27a', T: '#e05294' },
      map: [
        '................',
        '................',
        '...kkkkkkkkkk...',
        '..kCCCCCCCCCCk..',
        '.kCCcCCCCCCcCCk.',
        '.kCCCCYYYYCCCCk.',
        '.kkkkkkkkkkkkkk.',
        '.kWWdWWddWWdWWk.',
        '.kddEEddddEEddk.',
        '.kddddTTTTddddk.',
        '.kWWdWWddWWdWWk.',
        '.kkkkkkkkkkkkkk.',
        '.kCCCCYyyYCCCCk.',
        '.kCcCCCCCCCcCCk.',
        '..kkkkkkkkkkkk..',
        '................',
      ],
    },
    ladder: {
      colors: { F: '#57506a', f: '#4a445c', L: '#c49658', l: '#96702e', d: '#2a2438' },
      map: [
        'FFFddddddddddFFF',
        'FFdLddddddddLdFF',
        'FFdLddddddddLdFF',
        'FFdLLLLLLLLLLdFF',
        'FFdLddddddddLdFF',
        'FFdLddddddddLdFF',
        'FFdLLLLLLLLLLdFF',
        'FFdLddddddddLdFF',
        'FFdLddddddddLdFF',
        'FFdLLLLLLLLLLdFF',
        'FFdLddddddddLdFF',
        'FFdLddddddddLdFF',
        'FFdLLLLLLLLLLdFF',
        'FFdlddddddddldFF',
        'FFdlddddddddldFF',
        'FFFddddddddddFFF',
      ],
    },
    castle: {
      colors: { G: '#4e9e52', S: '#b4b2c8', s: '#8d8ba4', k: '#5c5a72', R: '#e05252', d: '#2a2438', Y: '#ffd94a' },
      map: [
        'GGGRGGGGGGGGRGGG',
        'GGGRRGGGGGGGRRGG',
        'GGGSGGGGGGGGSGGG',
        'GGSSSGSSSSGSSSGG',
        'GGSkSSSkkSSSkSGG',
        'GGSSSSSSSSSSSSGG',
        'GGSsSSsSSsSSsSGG',
        'GGSSSSSSSSSSSSGG',
        'GSSSSSSSSSSSSSSG',
        'GSsSSkddkSSSSsSG',
        'GSSSkddddkSSSSSG',
        'GSsSkddddkSSsSSG',
        'GSSSkddddkSSSSSG',
        'GSSSkdYddkSSSSSG',
        'GSSSkddddkSSSSSG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    murk: { // the Murk: fog that grew where light stopped reaching
      colors: { D: '#3a3f4d', d: '#2e3340', g: '#4a5063', h: '#585f75' },
      map: [
        'DDDdddDDDDddDDDD',
        'DdggDDDDggDDDDdD',
        'DghhgDDghhgDDDDD',
        'DDgggDDDgggDDdDD',
        'dDDDDdDDDDDghgDD',
        'DDghgDDDDdDgggDD',
        'DghhhgDDDDDDDDDd',
        'DDggggDDghgDDDDD',
        'dDDDDDDghhhgDDDD',
        'DDDdDDDDgggDDdDD',
        'DghgDDdDDDDDDDDD',
        'DgggDDDDDghgDDdD',
        'DDDDdDDDghhhgDDD',
        'dDDDDDDDDgggDDDD',
        'DDdDDghgDDDDDdDD',
        'DDDDDgggDDDDDDDD',
      ],
    },
    lighthouse: { // the Great Lighthouse, dark as a closed eye
      colors: { G: '#4e9e52', W: '#d8d4c8', w: '#aca89c', R: '#8a3d3d', r: '#6b2e2e', d: '#2a2438', k: '#5c5a72' },
      map: [
        'GGGGGGdddGGGGGGG',
        'GGGGGdkdkdGGGGGG',
        'GGGGGdddddGGGGGG',
        'GGGGGRRRRRGGGGGG',
        'GGGGGrRRRrGGGGGG',
        'GGGGGWWWWWGGGGGG',
        'GGGGGWwWWWGGGGGG',
        'GGGGGRRRRRGGGGGG',
        'GGGGGrRRRrGGGGGG',
        'GGGGGWWWWWGGGGGG',
        'GGGGWWwWWWWGGGGG',
        'GGGGWWWWwWWGGGGG',
        'GGGGRRRRRRRGGGGG',
        'GGGGrRRRRRrGGGGG',
        'GGGwwWWWWWwwGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    // ---- Wave 6.5 renderability pass: tiles that shipped invisible ----
    spireTower: { // the Clockwork Spire: brass tower, one big clock eye
      colors: { G: '#4e9e52', S: '#7a6a52', s: '#5e5140', B: '#c9a13e', b: '#a07f2c', W: '#f4e8c8', k: '#2a2438' },
      map: [
        'GGGGGGsSSsGGGGGG',
        'GGGGGsSSSSsGGGGG',
        'GGGGGSBBBBSGGGGG',
        'GGGGGSBWWBSGGGGG',
        'GGGGGSWkkWSGGGGG',
        'GGGGGSWkkWSGGGGG',
        'GGGGGSBWWBSGGGGG',
        'GGGGGSBBBBSGGGGG',
        'GGGGGsSSSSsGGGGG',
        'GGGGGSSssSSGGGGG',
        'GGGGGSSSSSSGGGGG',
        'GGGGsSSSSSSsGGGG',
        'GGGGSSsSSsSSGGGG',
        'GGGGSSSSSSSSGGGG',
        'GGGsSSSkkSSSsGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    hallTower: { // the Resonant Halls: a bell hall, doors like organ pipes
      colors: { G: '#4e9e52', P: '#7a5c9e', p: '#5e4579', B: '#c9a13e', b: '#a07f2c', k: '#2a2438' },
      map: [
        'GGGGGpPPPPpGGGGG',
        'GGGGpPPPPPPpGGGG',
        'GGGpPPpBBpPPpGGG',
        'GGGPPPBBBBPPPGGG',
        'GGGPPPBbbBPPPGGG',
        'GGGPPPpBBpPPPGGG',
        'GGGPPPPbbPPPPGGG',
        'GGGpPPPPPPPPpGGG',
        'GGGPPpPPPPpPPGGG',
        'GGGPPpPPPPpPPGGG',
        'GGGPPpPPPPpPPGGG',
        'GGpPPPPPPPPPPpGG',
        'GGPPpPkkkkPpPPGG',
        'GGPPpPkkkkPpPPGG',
        'GGpPPPPPPPPPPpGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    breakArch: { // the Sunken Breakwater: a stone arch over dark water
      colors: { G: '#4e9e52', S: '#8a8574', s: '#6b6656', W: '#2e5f8a', w: '#254b6e', k: '#1a2634' },
      map: [
        'GGGGGGGGGGGGGGGG',
        'GGGsSSSSSSSSsGGG',
        'GGsSSsSSSSsSSsGG',
        'GGSSsGGGGGGsSSGG',
        'GGSSGGGGGGGGSSGG',
        'GGSsGGkkkkGGsSGG',
        'GGSSGkkkkkkGSSGG',
        'GGSsGkkkkkkGsSGG',
        'GGSSGkwwwwkGSSGG',
        'GGSsGwWWWWwGsSGG',
        'GGSSGWWwWWWGSSGG',
        'GGSsGwWWWwWGsSGG',
        'GGSSGWwWWWwGSSGG',
        'GGsSsWWWwWWsSsGG',
        'GGGSSWwWWWwSSGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    clockDoor: { // a clock door: read the face, open the way
      colors: { F: '#57506a', S: '#6b5030', s: '#54402a', W: '#f4e8c8', w: '#d8cba4', k: '#2a2438', B: '#c9a13e' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FssSSSSSSSSSSssF',
        'FsSSSSSSSSSSSSsF',
        'FsSSWWWWWWWWSSsF',
        'FsSWwwwwwwwwWSsF',
        'FsSWwwwkwwwwWSsF',
        'FsSWwwwkwwwwWSsF',
        'FsSWwwwkkkwwWSsF',
        'FsSWwwwwwwwwWSsF',
        'FsSWwwwwwwwwWSsF',
        'FsSSWWWWWWWWSSsF',
        'FsSSSSSSSSSSSSsF',
        'FsSSSSSBBSSSSSsF',
        'FsSSSSSBBSSSSSsF',
        'FssSSSSSSSSSSssF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    echoDoor: { // an echo door: a bell above, tones to repeat
      colors: { F: '#57506a', S: '#5e4579', s: '#4a3660', B: '#c9a13e', b: '#a07f2c', k: '#2a2438' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FssSSSSSSSSSSssF',
        'FsSSSSSbbSSSSSsF',
        'FsSSSSbBBbSSSSsF',
        'FsSSSbBBBBbSSSsF',
        'FsSSSbBBBBbSSSsF',
        'FsSSSbBBBBbSSSsF',
        'FsSSSSbkkbSSSSsF',
        'FsSSSSSkkSSSSSsF',
        'FsSSSSSSSSSSSSsF',
        'FsSSkSSSSSSkSSsF',
        'FsSSkSSkkSSkSSsF',
        'FsSSkSSkkSSkSSsF',
        'FsSSSSSSSSSSSSsF',
        'FssSSSSSSSSSSssF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    gearPlate: { // a gear plate set into the floor — step to turn the gates
      colors: { F: '#57506a', f: '#4a445c', B: '#c9a13e', b: '#a07f2c', k: '#2a2438' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FfffffffffffffbF',
        'FfFFbFFbbFFbFFfF',
        'FfFbbbFbbFbbbFfF',
        'FfFFbBBBBBBbFFfF',
        'FfbbBBbBBbBBbbfF',
        'FfFbBbBBBBbBbFfF',
        'FfFbBBBkkBBBbFfF',
        'FfFbBBBkkBBBbFfF',
        'FfFbBbBBBBbBbFfF',
        'FfbbBBbBBbBBbbfF',
        'FfFFbBBBBBBbFFfF',
        'FfFbbbFbbFbbbFfF',
        'FfFFbFFbbFFbFFfF',
        'FfffffffffffffFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    // ---------- Wave 7: gear-gate readability (the plate's carry-over) ----------
    // The Spire's rotating gates used to be INVISIBLE: applyGearState rewrote
    // them to plain '#'/'.', so a kid stepping on the plate saw a distant wall
    // silently become floor — "very unclear what was going on" (playtest).
    // Now the A/B/C glyphs stay in the grid and render as these: obviously
    // mechanical, obviously not ordinary walls, and obviously open vs shut.
    // The • / •• / ••• pips that say WHICH gate this is are painted on top by
    // drawWorld (ui.js) — one sprite pair serves all three gates.
    gateShut: { // a brass, gear-toothed barrier — closed
      colors: { F: '#57506a', f: '#4a445c', B: '#c9a13e', b: '#a07f2c', d: '#6e5620', k: '#2a2438' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FkkkkkkkkkkkkkkF',
        'FkBbBbBbBbBbBbkF',
        'FkbdddddddddddbF',
        'FkBdBBdBBdBBdBkF',
        'FkbdBbdBbdBbdbbF',
        'FkBdBBdBBdBBdBkF',
        'FkbddddddddddddF',
        'FkBdBBdBBdBBdBkF',
        'FkbdBbdBbdBbdbbF',
        'FkBdBBdBBdBBdBkF',
        'FkbdddddddddddbF',
        'FkBbBbBbBbBbBbkF',
        'FkkkkkkkkkkkkkkF',
        'FfffffffffffffFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    gateOpen: { // the same gate, wound back into its frame — a recessed opening
      colors: { F: '#57506a', f: '#4a445c', B: '#c9a13e', b: '#a07f2c', k: '#2a2438', o: '#3a3450' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FBbkkkkkkkkkkbBF',
        'FbkooooooooooobF',
        'FkoooooooooooooF',
        'FkoooooooooooooF',
        'FkoooooooooooooF',
        'FkoooooooooooooF',
        'FkoooooooooooooF',
        'FkoooooooooooooF',
        'FkoooooooooooooF',
        'FkoooooooooooooF',
        'FkoooooooooooooF',
        'FbkooooooooooobF',
        'FBbkkkkkkkkkkbBF',
        'FfffffffffffffFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    resetLever: { // Gullwrack's repair-site reset lever — pull to re-spawn slabs
      colors: { F: '#57506a', f: '#4a445c', S: '#8d8ba4', s: '#5c5a72', B: '#7a5c2c', G: '#6ee87e', k: '#2a2438' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFFGGGGGFFFFFF',
        'FFFFGGkkkGGFFFFF',
        'FFFFGGkGkGGFFFFF',
        'FFFFGGkkkGGFFFFF',
        'FFFFFGGGGGFFFFFF',
        'FFFFFFFBFFFFFFFF',
        'FFFFFFFBFFFFFFFF',
        'FFFFFFBBFFFFFFFF',
        'FFFFsSSSsFFFFFFF',
        'FFFsSSSSSsFFFFFF',
        'FFsSSsssSSsFFFFF',
        'FFsSSSSSSSsFFFFF',
        'FFssssssssssFFFF',
        'FFfFFFFFFFFFfFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },

    // ---------- Wave 7: the Open Castle (interior) ----------
    hallFloor: { // polished flagstones — deliberately LIGHT and warm, so the
      // castle interior never reads as one more dungeon. (First draft used
      // wall-coloured joints and the whole room looked like brickwork.)
      colors: { A: '#8f819c', B: '#877991', C: '#a294ae', j: '#77697f' },
      map: [
        'jjjjjjjjjjjjjjjj',
        'jAAAAAAAjBBBBBBB',
        'jAAAAAAAjBBBBBBB',
        'jAACAAAAjBBBBBBB',
        'jAAAAAAAjBBBBCBB',
        'jAAAAAAAjBBBBBBB',
        'jAAAAAAAjBBBBBBB',
        'jAAAAAAAjBBBBBBB',
        'jjjjjjjjjjjjjjjj',
        'jBBBBBBBjAAAAAAA',
        'jBBBBBBBjAAAAAAA',
        'jBBBBCBBjAAAAAAA',
        'jBBBBBBBjAAACAAA',
        'jBBBBBBBjAAAAAAA',
        'jBBBBBBBjAAAAAAA',
        'jBBBBBBBjAAAAAAA',
      ],
    },
    plinth: { // a Gallery plinth — one of the ten recovered treasures rests here
      colors: { A: '#8f819c', k: '#4a4458', S: '#cfc6e8', s: '#9a92b8', Y: '#ffd94a', y: '#c9a13e' },
      map: [
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAyYYYYyAAAAA',
        'AAAAyYYYYYYyAAAA',
        'AAAAyYYyyYYyAAAA',
        'AAAAAyYYYYyAAAAA',
        'AAAAAAyYYyAAAAAA',
        'AAAAsSSSSSSsAAAA',
        'AAAsSSSSSSSSsAAA',
        'AAAAsSSSSSSsAAAA',
        'AAAAAsSSSSsAAAAA',
        'AAAAAsSSSSsAAAAA',
        'AAAAsSSSSSSsAAAA',
        'AAAsSSSSSSSSsAAA',
        'AAAkkkkkkkkkkAAA',
        'AAAAAAAAAAAAAAAA',
      ],
    },
    crestBoard: { // the Hall of Heroes — every adventurer's crest, side by side
      colors: { A: '#8f819c', k: '#3a3450', B: '#8a5a2c', b: '#66421f', Y: '#ffd94a', S: '#cfc6e8', G: '#6ee87e' },
      map: [
        'AAAAAAAAAAAAAAAA',
        'ABBBBBBBBBBBBBBA',
        'ABkkkkkkkkkkkkBA',
        'ABkYYkSSkGGkYYkA',
        'ABkYYkSSkGGkYYkA',
        'ABkkkkkkkkkkkkBA',
        'ABkSSkGGkYYkSSkA',
        'ABkSSkGGkYYkSSkA',
        'ABkkkkkkkkkkkkBA',
        'ABkGGkYYkSSkGGkA',
        'ABkGGkYYkSSkGGkA',
        'ABkkkkkkkkkkkkBA',
        'ABBBBBBBBBBBBBBA',
        'AAbbbbbbbbbbbbAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
      ],
    },
    throne: { // the seat itself — empty, and waiting
      colors: { A: '#8f819c', k: '#3a3450', R: '#b8434f', r: '#8a2f39', Y: '#ffd94a', y: '#c9a13e' },
      map: [
        'AAAAAAAAAAAAAAAA',
        'AAAAyYYYYYYyAAAA',
        'AAAyYYYYYYYYyAAA',
        'AAAyYrRRRRryYAAA',
        'AAAyYrRRRRryYAAA',
        'AAAyYrRRRRryYAAA',
        'AAAyYrRRRRryYAAA',
        'AAAyYrRRRRryYAAA',
        'AAAyYYYYYYYYyAAA',
        'AAyYRRRRRRRRYyAA',
        'AAyYRRRRRRRRYyAA',
        'AAyYYYYYYYYYYyAA',
        'AAAykkAAAAkkyAAA',
        'AAAykkAAAAkkyAAA',
        'AAAkkkAAAAkkkAAA',
        'AAAAAAAAAAAAAAAA',
      ],
    },
    banner: { // a hanging banner — the castle finally dressed for company
      colors: { W: '#4a4458', k: '#3a3450', B: '#5b4bb8', b: '#43379a', Y: '#ffd94a' },
      map: [
        'kkkkkkkkkkkkkkkk',
        'kWWWWWWWWWWWWWWk',
        'kWkkkkkkkkkkkkWk',
        'kWkBBBBBBBBBBkWk',
        'kWkBBBBYBBBBBkWk',
        'kWkBBBYYYBBBBkWk',
        'kWkBBYYYYYBBBkWk',
        'kWkBBBYYYBBBBkWk',
        'kWkBBBBYBBBBBkWk',
        'kWkBBBBBBBBBBkWk',
        'kWkbBBBBBBBBbkWk',
        'kWkbbBBBBBBbbkWk',
        'kWkbbbBBBBbbbkWk',
        'kWkbbbbBBbbbbkWk',
        'kWWWWWbbbbWWWWWk',
        'kkkkkkkkkkkkkkkk',
      ],
    },
    castleDoor: { // the great doors, from the inside — the way back out
      colors: { A: '#8f819c', k: '#3a3450', B: '#8a5a2c', b: '#66421f', Y: '#ffd94a', S: '#cfc6e8' },
      map: [
        'AAAAAAAAAAAAAAAA',
        'AAAkkkkkkkkkkAAA',
        'AAkBBBBBBBBBBkAA',
        'AkBBbBBBBBBbBBkA',
        'AkBBbBBBBBBbBBkA',
        'AkBBbBBYYBBbBBkA',
        'AkBBbBYSSYBbBBkA',
        'AkBBbBYSSYBbBBkA',
        'AkBBbBBYYBBbBBkA',
        'AkBBbBBBBBBbBBkA',
        'AkBBbBBBBBBbBBkA',
        'AkBBbBBBBBBbBBkA',
        'AkBBbBBBBBBbBBkA',
        'AkkkkkkkkkkkkkkA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
      ],
    },
    mathmaker: { // the MathMaker himself — finally drawn, for his own ending
      colors: { H: '#3d6bb8', h: '#2c4e8a', B: '#e8e4d4', S: '#f0c8a0', k: '#2a2438', Y: '#ffd94a', W: '#cfc6e8' },
      map: [
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '....SSSSSSSS....',
        '....SkSSSSkS....',
        '....SSSSSSSS....',
        '.....SkkkkS.....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '..WBBBBYYBBBBW..',
        '..WBBBBYYBBBBW..',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBB..BBBB...',
        '...kkkk..kkkk...',
        '...kkkk..kkkk...',
      ],
    },

    singStone: { // a singing stone: chimes a scale note underfoot
      colors: { F: '#57506a', f: '#4a445c', S: '#8a92b8', s: '#6b7394', W: '#dce8ec' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFFFFFFWFFFFFFFF',
        'FFFFFFFFFFWFFFFF',
        'FFFFFsSSsFFFFFFF',
        'FFFFsSSSSsFFFFFF',
        'FFFFsSWSSsFFFFFF',
        'FFFsSSWSSSsFFFFF',
        'FFFsSSSSSSsFFFFF',
        'FFFsSSSSsSsFFFFF',
        'FFsSSSSSSSSsFFFF',
        'FFsSSsSSSSSsFFFF',
        'FFsSSSSSSsSsFFFF',
        'FfsssssssssssfFF',
        'FFffffffffffFFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    slab: { // a pushable stone slab — shoulder in and heave
      colors: { F: '#57506a', S: '#9a938a', s: '#7d766c', w: '#b8b2a8', k: '#3f394f' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FkkkkkkkkkkkkkkF',
        'FkwwwwwwwwwwwskF',
        'FkwSSSSSSSSSSskF',
        'FkwSSSSSSSSSSskF',
        'FkwSSsSSSSsSSskF',
        'FkwSSSSSSSSSSskF',
        'FkwSSSSsSSSSSskF',
        'FkwSSSSSSSSSSskF',
        'FkwSsSSSSSSsSskF',
        'FkwSSSSSSSSSSskF',
        'FkwSSSSsSSSSSskF',
        'FkwSSSSSSSSSSskF',
        'FksssssssssssskF',
        'FkkkkkkkkkkkkkkF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    brokenFloor: { // shattered floor — impassable until a slab mends it
      colors: { F: '#57506a', f: '#4a445c', d: '#332e42', k: '#231f30' },
      map: [
        'FFFfFFFFFFfFFFFF',
        'FfdkdFFFfdkdfFFF',
        'FFdkkdFFdkkdFFfF',
        'FFFdkkdkkkdFFFFF',
        'FfFFdkkkkdFFFfFF',
        'FFFdkkdkkkdFFFFF',
        'FFdkkdFFdkkdFFFF',
        'FfdkdFFFFdkkdfFF',
        'FFdkFFfFFFdkdFFF',
        'FFFdkdFFFdkdFFfF',
        'FfFFdkkdkkdFFFFF',
        'FFFFFdkkkdFFFFFF',
        'FFfFdkkdkkdFfFFF',
        'FFFdkdFFFdkdFFFF',
        'FfFFFFFFFFFFFfFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    petPup: { // the Compass Pup (blue egg)
      colors: { B: '#a8794a', b: '#8a5f38', W: '#f2ede4', k: '#1a1626', N: '#3d2c1e', R: '#e05252' },
      map: [
        '............',
        '.bb......bb.',
        '.bBb....bBb.',
        '.bBBbbbbBBb.',
        '.bBBBBBBBBb.',
        '.bBkBBBBkBb.',
        '.bBBBNNBBBb.',
        '..bBBNNBBb..',
        '..bBBBBBBbb.',
        '.bBBBBBBBBb.',
        '.bBb.bb.bBb.',
        '............',
      ],
    },
    petCat: { // the Sprout Cat (green egg)
      colors: { B: '#6fae62', b: '#54874a', W: '#e4f2dc', k: '#1a1626', P: '#e08ab0', L: '#3d6b34' },
      map: [
        '..L.........',
        '..Lb.....b..',
        '.bBBb...bBb.',
        '.bBBBbbbBBb.',
        '.bBBBBBBBBb.',
        '.bBkBBBBkBb.',
        '.bBBBPPBBBb.',
        '..bBBBBBBb..',
        '..bBBBBBBb..',
        '.bBBBBBBBBbb',
        '.bBb.bb.bBb.',
        '............',
      ],
    },
    petNewt: { // the Ember Newt (rose egg)
      colors: { B: '#e0854a', b: '#b8642f', W: '#f9e0c8', k: '#1a1626', Y: '#ffd94a', R: '#c23c2c' },
      map: [
        '............',
        '.....YY.....',
        '....bYYb....',
        '...bBBBBb...',
        '..bBBBBBBb..',
        '..bBkBBkBb..',
        '..bBBBBBBb..',
        '..bBWWWWBb..',
        '..bBBBBBBbb.',
        '.bBBb..bBBbb',
        '.bb......bbb',
        '............',
      ],
    },
    chute: { // a drop chute: dark, deep, and strictly one-way
      colors: { F: '#57506a', f: '#4a445c', d: '#241f36', e: '#12101c', B: '#6b4522', Y: '#ffd94a' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FfFFFFFFFFFFFfFF',
        'FFBBBBBBBBBBBBFF',
        'FFBddddddddddBFF',
        'FFBddeeeeeeddBFF',
        'FFBdeeeeeeeedBFF',
        'FFBdeeYeeYeedBFF',
        'FFBdeeeYYeeedBFF',
        'FFBdeeeYYeeedBFF',
        'FFBdeeYeeYeedBFF',
        'FFBdeeeeeeeedBFF',
        'FFBddeeeeeeddBFF',
        'FFBddddddddddBFF',
        'FFBBBBBBBBBBBBFF',
        'FfFFFFFFFFFFFFfF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    ship: { // the Compass Rose under sail (for the voyage scene)
      colors: { W: '#f2ede4', w: '#d8cdb4', B: '#8a5a2c', b: '#6b4522', k: '#523618', R: '#e05252' },
      map: [
        '.......k........',
        '.......kWW......',
        '.......kWWWW....',
        '.......kWWWWWW..',
        '..WWWWWkWWWWW...',
        '...WWWWkWWW.....',
        '.....WWkW.......',
        '.......k....R...',
        '.......k........',
        '.bBBBBBBBBBBBb..',
        '..bBBBBBBBBBb...',
        '...bbBBBBBbb....',
        '................',
        '................',
        '................',
        '................',
      ],
    },
    pier: { // wooden pier reaching into the western sea
      colors: { G: '#4e9e52', W: '#3d6b8a', w: '#2c5068', B: '#8a5a2c', b: '#6b4522', k: '#523618' },
      map: [
        'WWWWWWWWWWWWWWWW',
        'WWwWWBBBBBBWWwWW',
        'WWWWWBbBbBBWWWWW',
        'WwWWWBBBBbBWWWWW',
        'WWWWkBbBBBBkWWwW',
        'WWWWkBBBbBBkWWWW',
        'WwWWWBBBBBBWWWWW',
        'WWWWWBbBBbBWwWWW',
        'WWWWkBBBBBBkWWWW',
        'WWwWkBBbBBBkWWwW',
        'GGGGGBBBBbBGGGGG',
        'GGGGGBbBBBBGGGGG',
        'GGGGGBBBBBBGGGGG',
        'GGGGGGBBBBGGGGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    wallCrack: { // a wall with a hairline crack — worth a nudge
      colors: { K: '#4a4258', k: '#332c44', h: '#5c5470', c: '#6e6488' },
      map: [
        'KKKKKKKkKKKKKKKK',
        'KhKKKKKkKKKKhKKK',
        'KKKKKKKcKKKKKKKK',
        'kkkkkkkckkkkkkkk',
        'KKKkKKKcKKKkKKKK',
        'KKKkKKcKKKKkKKKK',
        'KKKkKKcKKKKkKKKK',
        'kkkkkkckkkkkkkkk',
        'KKKKKKcKKKKKKKKK',
        'KhKKKKKcKKKKKhKK',
        'KKKKKKKcKKKKKKKK',
        'kkkkkkkckkkkkkkk',
        'KKKkKKKKcKKkKKKK',
        'KKKkKKKKcKKkKKKK',
        'KKKkKKKKcKKkKKKK',
        'kkkkkkkkckkkkkkk',
      ],
    },
    pool: { // a glinting tide pool set into the cave floor
      colors: { F: '#57506a', f: '#4a445c', W: '#2c8a8a', w: '#1d6468', s: '#7ee0d4' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFfwwwwwFFFFFF',
        'FFFwwWWWWwwwFFFF',
        'FFwWWWWsWWWWwFFF',
        'FfwWWsWWWWWWwwFF',
        'FwWWWWWWWWsWWwFF',
        'FwWWsWWWWWWWWwFF',
        'FwWWWWWWsWWWWwFF',
        'FFwWWWWWWWWWwfFF',
        'FFwWsWWWWsWWwFFF',
        'FFFwwWWWWWwwFFFF',
        'FFFFwwWWwwwFFFFF',
        'FFFFFfwwwFFFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFfFFFFFFFFfFFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    urchin: { // spiny urchins carpeting the floor: crossing stings
      colors: { F: '#57506a', f: '#4a445c', U: '#2b1a33', u: '#4a2c5c', p: '#8a5ca8' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFuFFFFFFFuFFFFF',
        'FuUUuFFFFuUUuFFF',
        'FUUpUUFFuUUUUuFF',
        'FuUUUuFFFuUpUFFF',
        'FFuUuFFFFFuUuFFF',
        'FFFuFFFFFFFuFFFF',
        'FFFFFFuFFFFFFFFF',
        'FFFFFuUuFFFFFFFF',
        'FFFFuUUUuFFFuFFF',
        'FFFFuUpUuFFuUuFF',
        'FFFFFuUuFFuUUUuF',
        'FFFFFFuFFFuUpUuF',
        'FFFFFFFFFFFuUuFF',
        'FFfFFFFFFFFFuFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    slick: { // slick wet rock: step on and you skid
      colors: { F: '#57506a', S: '#6ea8b8', s: '#578a9c', h: '#a8dce8' },
      map: [
        'SSSSSSSSSSSSSSSS',
        'SShSSSSSsSSSSSSS',
        'SSShhSSSSSSShSSS',
        'SSSSSSSSSShhSSSS',
        'SsSSSShhSSSSSSSS',
        'SSSSShhSSSSSSsSS',
        'SSSSSSSSSSSSSSSS',
        'SShSSSSSShhSSSSS',
        'SSShhSSSSSShSSSS',
        'SSSSSSsSSSSSSSSS',
        'SsSSSSSSSSSShhSS',
        'SSSSShSSSSShSSSS',
        'SSSShhSSSSSSSSsS',
        'SSSSSSSSsSSSSSSS',
        'SSsSSSSSSSShSSSS',
        'SSSSSSSSSSSSSSSS',
      ],
    },
    pad: { // a glowing tide pad: stand on it and whoosh
      colors: { F: '#57506a', f: '#4a445c', R: '#5ee8c8', r: '#2c8a7a', d: '#1d5a50' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFFrRRRRrFFFFF',
        'FFFrRRrrrrRRrFFF',
        'FFrRrfFFFFfrRrFF',
        'FrRrFFFFFFFFrRrF',
        'FrRfFFrRRrFFfRrF',
        'FRrFFrRddRrFFrRF',
        'FRrFFRdFFdRFFrRF',
        'FRrFFRdFFdRFFrRF',
        'FRrFFrRddRrFFrRF',
        'FrRfFFrRRrFFfRrF',
        'FrRrFFFFFFFFrRrF',
        'FFrRrfFFFFfrRrFF',
        'FFFrRRrrrrRRrFFF',
        'FFFFFrRRRRrFFFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    keyTile: { // a key, just lying there. Suspiciously convenient.
      colors: { F: '#57506a', f: '#4a445c', Y: '#ffd94a', y: '#d8a03c', k: '#8a6a1c' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFFYYYFFFFFFFFFF',
        'FFYykyYFFFFFFFFF',
        'FFYkFkYFFFFFFFFF',
        'FFYykyYFFFFFFFFF',
        'FFFYYYyFFFFFFFFF',
        'FFFFFyYyFFFFFFFF',
        'FFFFFFyYyFFFFFFF',
        'FFFFFFFyYyYFFFFF',
        'FFFFFFFFyYyYFFFF',
        'FFFFFFFFFyYFYFFF',
        'FFFFFFFFFFFFFFFF',
        'FFfFFFFFFFFfFFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    lockDoor: { // an iron-banded door with a big golden lock
      colors: { K: '#4a4258', k: '#332c44', D: '#6e5a8a', d: '#574570', Y: '#ffd94a', y: '#8a6a1c' },
      map: [
        'KKKKKKKKKKKKKKKK',
        'KKKKkkkkkkkkKKKK',
        'KKKkDDDDDDDDkKKK',
        'KKkDDdDDDDdDDkKK',
        'KKkDDDDDDDDDDkKK',
        'KKkddddddddddkKK',
        'KKkDDDDDDDDDDkKK',
        'KKkDDDYYYYDDDkKK',
        'KKkDDYYyyYYDDkKK',
        'KKkDDYyyyyYDDkKK',
        'KKkDDYYyyYYDDkKK',
        'KKkDDDYyyYDDDkKK',
        'KKkddddddddddkKK',
        'KKkDDdDDDDdDDkKK',
        'KKkDDDDDDDDDDkKK',
        'kkkkkkkkkkkkkkkk',
      ],
    },
    lever: { // an old stone-set lever, begging to be pulled
      colors: { F: '#57506a', f: '#4a445c', S: '#8d8ba4', s: '#5c5a72', B: '#8a5a2c', Y: '#ffd94a' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFFFFFFFYFFFFF',
        'FFFFFFFFFYYYFFFF',
        'FFFFFFFFFFYFFFFF',
        'FFFFFFFFFBFFFFFF',
        'FFFFFFFFBBFFFFFF',
        'FFFFFFFBBFFFFFFF',
        'FFFFFFBBFFFFFFFF',
        'FFFFFBBFFFFFFFFF',
        'FFFFsSSsFFFFFFFF',
        'FFFsSSSSsFFFFFFF',
        'FFsSSssSSsFFFFFF',
        'FFsSSSSSSsFFFFFF',
        'FFssssssssFFFFFF',
        'FFfFFFFFFFFfFFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    gate: { // heavy stone bars: some lever, somewhere, moves them
      colors: { F: '#57506a', S: '#8d8ba4', s: '#5c5a72', k: '#332c44' },
      map: [
        'ssssssssssssssss',
        'sSSskSSskSSskSSs',
        'sSSskSSskSSskSSs',
        'sSsskSsskSsskSss',
        'sSSskSSskSSskSSs',
        'sSSskSSskSSskSSs',
        'ssssssssssssssss',
        'sSSskSSskSSskSSs',
        'sSsskSsskSsskSss',
        'sSSskSSskSSskSSs',
        'sSSskSSskSSskSSs',
        'ssssssssssssssss',
        'sSSskSSskSSskSSs',
        'sSSskSsskSSskSss',
        'sSSskSSskSSskSSs',
        'ssssssssssssssss',
      ],
    },
    stairsDown: { // steps descending into the dark
      colors: { F: '#57506a', f: '#4a445c', d: '#2a2438', e: '#1a1626' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FffffffffffffffF',
        'FfFFFFFFFFFFFFfF',
        'FfFddddddddddFfF',
        'FfFdffffffffdFfF',
        'FfFdfddddddfdFfF',
        'FfFdfdeeeedfdFfF',
        'FfFdfdeeeedfdFfF',
        'FfFdfdeeeedfdFfF',
        'FfFdfdeeeedfdFfF',
        'FfFdfddddddfdFfF',
        'FfFdffffffffdFfF',
        'FfFddddddddddFfF',
        'FfFFFFFFFFFFFFfF',
        'FffffffffffffffF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    stairsUp: { // steps climbing back toward daylight
      colors: { F: '#57506a', f: '#4a445c', L: '#8d8ba4', l: '#6e6c84', Y: '#c4c2d8' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FffffffffffffffF',
        'FfYYYYYYYYYYYYfF',
        'FfYLLLLLLLLLLYfF',
        'FfYLllllllllLYfF',
        'FfYLlLLLLLLlLYfF',
        'FfYLlLllllLlLYfF',
        'FfYLlLlffLLlLYfF',
        'FfYLlLlffLLlLYfF',
        'FfYLlLllllLlLYfF',
        'FfYLlLLLLLLlLYfF',
        'FfYLllllllllLYfF',
        'FfYLLLLLLLLLLYfF',
        'FfYYYYYYYYYYYYfF',
        'FffffffffffffffF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    board: { // the notice board: planks, pinned paper notices, sturdy legs
      colors: { G: '#4e9e52', B: '#8a5a2c', b: '#6b4522', W: '#f2ede4', w: '#d8cdb4', Y: '#ffd94a', R: '#e05252' },
      map: [
        'GGGGGGGGGGGGGGGG',
        'GGBBBBBBBBBBBBGG',
        'GGBbbbbbbbbbbBGG',
        'GGBbWWwbbWWWbBGG',
        'GGBbWwWbRWwWbBGG',
        'GGBbWWWbbWWwbBGG',
        'GGBbwWWbbwWWbBGG',
        'GGBbbbbbbbbbbBGG',
        'GGBbWWWwbYYwbBGG',
        'GGBbWwWWbbbbbBGG',
        'GGBbbbbbbbbbbBGG',
        'GGBBBBBBBBBBBBGG',
        'GGGGBBGGGGBBGGGG',
        'GGGGBBGGGGBBGGGG',
        'GGGGBBGGGGBBGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    shop: {
      colors: { G: '#4e9e52', R: '#e05252', W: '#f2ede4', B: '#8a5a2c', b: '#6b4522', d: '#2a2438', Y: '#ffd94a' },
      map: [
        'GGGGGGGGGGGGGGGG',
        'GGRWRWRWRWRWRGGG',
        'GRWRWRWRWRWRWRGG',
        'GRRRRRRRRRRRRRGG',
        'GGBGGGGGGGGGBGGG',
        'GGBGGGGGGGGGBGGG',
        'GGBGYGGGGGGGBGGG',
        'GGBBBBBBBBBBBGGG',
        'GGBbbBbbBbbBBGGG',
        'GGBBBBBBBBBBBGGG',
        'GGBbbBddbBbbBGGG',
        'GGBBBBddbBBBBGGG',
        'GGBbbBddbBbbBGGG',
        'GGBBBBBBBBBBBGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    inn: {
      colors: { G: '#4e9e52', R: '#c05a3c', r: '#96432a', W: '#efe6d4', w: '#d8cdb4', d: '#2a2438', Y: '#ffd94a', k: '#5c4a38' },
      map: [
        'GGGGGGGGGGGGGGGG',
        'GGGGGGRRGGGGGGGG',
        'GGGGRRRRRRGGGGGG',
        'GGGRRrRRRRRGGGGG',
        'GGRRRRRRrRRRGGGG',
        'GRRrRRRRRRRRRGGG',
        'GRRRRRRRRrRRRGGG',
        'GGWWWWWWWWWWGGGG',
        'GGWwWWYYWWwWGGGG',
        'GGWWWWYYWWWWGGGG',
        'GGWwWWWWWWwWGGGG',
        'GGWWWddWWWWWGGGG',
        'GGWwWddWWkkWGGGG',
        'GGWWWddWWkkWGGGG',
        'GGWWWddWWWWWGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    hole: {
      colors: { G: '#4e9e52', g: '#3f8746', d: '#1c1830', D: '#2c2544', m: '#3a3354' },
      map: [
        'GGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGgddddddgGGGG',
        'GGGddddddddddGGG',
        'GGddDDddddDDddGG',
        'GGdDdddddddddDGG',
        'GdddddddddddddgG',
        'GddddddddddddddG',
        'GddddddddddddddG',
        'GdddddddddddddGG',
        'GGddddddddddddGG',
        'GGmddddddddddGGG',
        'GGGmmddddddmGGGG',
        'GGGGGmmmmmmGGGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },

    // ===== the hero (a proper knight!) =====
    hero: {
      colors: {
        k: '#1a1626', P: '#e05252', H: '#c4d0e4', h: '#8b97b0', F: '#f2c9a0',
        A: '#9aa6c0', a: '#6e7a96', L: '#5a6378', B: '#3f4657', W: '#eef2fa',
        G: '#d8a03c',
      },
      map: [
        '......PP........',
        '.....PPPP.......',
        '....kHHHHk......',
        '...kHHHHHHk.....',
        '...kHhFFhHk.....',
        '...kHFFFFHk..W..',
        '....kHHHHk...W..',
        '...kAAAAAAk..W..',
        '..kAAAAAAAAk.W..',
        '..kaAAAAAAGGGW..',
        '..kaAAAAAAkGG...',
        '...kAAAAAAk.....',
        '...kLLLLLLk.....',
        '...kLLkkLLk.....',
        '...kBBk.kBBk....',
        '..kkkk..kkkk....',
      ],
    },
    hero2: {
      colors: {
        k: '#1a1626', P: '#e05252', H: '#c4d0e4', h: '#8b97b0', F: '#f2c9a0',
        A: '#9aa6c0', a: '#6e7a96', L: '#5a6378', B: '#3f4657', W: '#eef2fa',
        G: '#d8a03c',
      },
      map: [
        '......PP........',
        '.....PPPP.......',
        '....kHHHHk......',
        '...kHHHHHHk.....',
        '...kHhFFhHk.....',
        '...kHFFFFHk..W..',
        '....kHHHHk...W..',
        '...kAAAAAAk..W..',
        '..kAAAAAAAAk.W..',
        '..kaAAAAAAGGGW..',
        '..kaAAAAAAkGG...',
        '...kAAAAAAk.....',
        '...kLLLLLLk.....',
        '....kLLLLk......',
        '....kBBBBk......',
        '....kkkkkk......',
      ],
    },

    // ===== monsters (palette-swapped per dungeon) =====
    slime: {
      colors: { k: '#143318', A: '#52c45a', B: '#3a9642', W: '#a5e8a9', E: '#ffffff', e: '#1a1626', M: '#2c7534' },
      map: [
        '................',
        '................',
        '......kkkk......',
        '....kkAAAAkk....',
        '...kAAWWAAAAk...',
        '..kAWWAAAAAAAk..',
        '..kAWAAAAAAAAk..',
        '.kAAAAAAAAAAAAk.',
        '.kAAEeAAAAEeAAk.',
        'kAAAEeAAAAEeAAAk',
        'kAAAAAAAAAAAAAAk',
        'kAAAAMMMMMMAAAAk',
        'kAABAAMMMMAABAAk',
        'kBAABBAAAABBAABk',
        '.kkBBBBBBBBBBkk.',
        '...kkkkkkkkkk...',
      ],
    },
    rat: {
      colors: { k: '#241a14', A: '#8a7466', B: '#6b584c', E: '#e05252', F: '#d8b8a8', T: '#c49688', W: '#f2ede4' },
      map: [
        '................',
        '................',
        '....kk....kk....',
        '...kFFk..kFFk...',
        '...kFFFkkFFFk...',
        '....kAAAAAAk....',
        '...kAAAAAAAAk...',
        '..kAAEkAAkEAAk..',
        '..kAAAAAAAAAAk..',
        '.kAAAAAkkAAAAAk.',
        '.kAAAAAAAAAAAkT.',
        '.kBAAAAAAAABkTT.',
        '.kABAAAAAABAkT..',
        '..kAAWWWWAAkT...',
        '...kkWkkWkkT....',
        '....kk..kk......',
      ],
    },
    bat: {
      colors: { k: '#1c1428', A: '#6b5490', B: '#523c74', E: '#ffd94a', W: '#f2ede4', m: '#3f2c5c' },
      map: [
        '................',
        '.kk..........kk.',
        'kAAk........kAAk',
        'kAAAk......kAAAk',
        'kAAAAk.kk.kAAAAk',
        'kAmAAkkAAkkAAmAk',
        'kAAAAAAAAAAAAAAk',
        '.kAAAkAAAAkAAAk.',
        '.kAmAAEkkEAAmAk.',
        '..kAAAAAAAAAAk..',
        '..kAAkWAAWkAAk..',
        '...kAAkWWkAAk...',
        '....kAAAAAAk....',
        '.....kAAAAk.....',
        '......kkkk......',
        '................',
      ],
    },
    spider: {
      colors: { k: '#181420', A: '#4a3f5c', B: '#382f47', E: '#e05252', L: '#2c2438', W: '#8d80a4' },
      map: [
        '................',
        '.L....L..L....L.',
        '.L...L....L...L.',
        '..L..L....L..L..',
        '..L.kkkkkkkk.L..',
        '...kAAAAAAAAk...',
        'LLLkAWAAAAWAkLLL',
        '..kAAAAAAAAAAk..',
        '..kAEkAAAAkEAk..',
        'LLkAAEkAAkEAAkLL',
        '..kAAAAAAAAAAk..',
        '.L.kABAABAABk.L.',
        '.L..kkkkkkkk..L.',
        '.L..L......L..L.',
        'L...L......L...L',
        '................',
      ],
    },
    skeleton: {
      colors: { k: '#1a1626', W: '#e8e4d8', w: '#c4bfa8', E: '#52c4c4', R: '#8a8578' },
      map: [
        '.....kkkkkk.....',
        '....kWWWWWWk....',
        '...kWWWWWWWWk...',
        '...kWEkWWkEWk...',
        '...kWWWWWWWWk...',
        '....kWkkkkWk....',
        '.....kwwwwk.....',
        '...kkkWWWWkkk...',
        '..kWkwWwwWwkWk..',
        '..kWkWWWWWWkWk..',
        '..kwkwWwwWwkwk..',
        '..kWk.wWWw.kWk..',
        '.......ww.......',
        '.....kwkkwk.....',
        '.....kwk.kwk....',
        '....kkk..kkk....',
      ],
    },
    ghost: {
      colors: { k: '#2a2444', A: '#d8d4f0', B: '#b0abd4', E: '#1a1626', m: '#8d88b8' },
      map: [
        '................',
        '......kkkk......',
        '....kkAAAAkk....',
        '...kAAAAAAAAk...',
        '..kAAAAAAAAAAk..',
        '..kAAEkAAkEAAk..',
        '.kAAAEkAAkEAAAk.',
        '.kAAAAAAAAAAAAk.',
        '.kAAAAkEEkAAAAk.',
        '.kAAAAAkkAAAAAk.',
        '.kABAAAAAAAABAk.',
        '.kAAAAAABAAAAAk.',
        '.kAABAAAAAABAAk.',
        '.kmAkAmBkABkAmk.',
        '..kk.kAAk.kAk...',
        '......kk...k....',
      ],
    },
    golem: {
      colors: { k: '#1f1a14', A: '#8a8578', B: '#6b665a', E: '#ffb84a', m: '#524e44', W: '#a8a494' },
      map: [
        '....kkkkkkkk....',
        '...kAAAAAAAAk...',
        '..kAWAAAAAAWAk..',
        '..kAAEkAAkEAAk..',
        '..kAAAAAAAAAAk..',
        '..kAAAkkkkAAAk..',
        '.kkAAAAAAAAAAkk.',
        'kAAkAAABBAAAkAAk',
        'kABkABAAAABAkBAk',
        'kAAkAAAmmAAAkAAk',
        'kmAkABAAAABAkAmk',
        'kkkkAAAAAAAAkkkk',
        '...kABAABAABk...',
        '...kkAAkkAAkk...',
        '..kAAAk..kAAAk..',
        '..kkkkk..kkkkk..',
      ],
    },
    mage: {
      colors: { k: '#161226', H: '#6b4fc0', h: '#523a99', A: '#3f3366', E: '#ffd94a', F: '#0e0b1c', S: '#c49658', s: '#96702e' },
      map: [
        '.......kk.......',
        '......kHHk......',
        '.....kHHHHk.....',
        '.....kHhHHk.....',
        '....kHHHHHHk....',
        '...kHHHhHHHHk...',
        '..kkkkkkkkkkkk..',
        '...kFFFFFFFFk.S.',
        '...kFEkFFkEFk.S.',
        '...kFFFFFFFFk.S.',
        '..kAAAAAAAAAAkS.',
        '..kAhAAAAAAhAkS.',
        '.kAAAAAAAAAAAkS.',
        '.kAhAAAAAAAhAkS.',
        '.kAAAAAAAAAAAkS.',
        '.kkkkkkkkkkkkkS.',
      ],
    },
    snake: {
      colors: { k: '#14240f', A: '#5aa838', B: '#437c2c', E: '#e05252', T: '#e05252', W: '#c4e0a8', Y: '#ffd94a' },
      map: [
        '.....kkkk.......',
        '....kAAAAk......',
        '...kAAAAAAk.....',
        '...kAEkAEkk.....',
        '...kAAAAAAk..T..',
        '...kAWWAAAkkT...',
        '...kAAAAAAAkT...',
        '....kAAAAAAk....',
        '.....kBAAAAk....',
        '..kkkkAAAAAk....',
        '.kAAAAAAAABk....',
        'kAABAAAAAABk....',
        'kABAAkkkAABk....',
        'kAAAAkkkAAAk....',
        '.kAAAAAAAAk.....',
        '..kkkkkkkk......',
      ],
    },

    bridge: {
      colors: { W: '#2f6fc4', r: '#5f3d1c', P: '#b0763e', p: '#8a5a2c', h: '#c98f52' },
      map: [
        'WWWWWWWWWWWWWWWW',
        'rrrrrrrrrrrrrrrr',
        'PPPpPPPPpPPPPpPP',
        'PPPpPPPPpPPPPpPP',
        'hhhphhhhphhhhphh',
        'PPPpPPPPpPPPPpPP',
        'PPPpPPPPpPPPPpPP',
        'pppppppppppppppp',
        'PPpPPPPpPPPPpPPP',
        'PPpPPPPpPPPPpPPP',
        'hhphhhhphhhhphhh',
        'PPpPPPPpPPPPpPPP',
        'PPpPPPPpPPPPpPPP',
        'rrrrrrrrrrrrrrrr',
        'WWWWWWWWWWWWWWWW',
        'WWWWWWWWWWWWWWWW',
      ],
    },

    // ===== townsfolk =====
    villager: {
      colors: { k: '#1a1626', H: '#8a5a2c', F: '#f2c9a0', A: '#5a8a4a', a: '#43683a', L: '#6b584c', B: '#3f4657' },
      map: [
        '................',
        '.....kkkkkk.....',
        '....kHHHHHHk....',
        '....kHFFFFHk....',
        '....kFkFFkFk....',
        '....kFFFFFFk....',
        '.....kFFFFk.....',
        '....kAAAAAAk....',
        '...kAAAAAAAAk...',
        '...kAFAAAAFAk...',
        '...kaAAAAAAak...',
        '....kAAAAAAk....',
        '....kaAAAAak....',
        '....kLLkkLLk....',
        '....kLLk.kLLk...',
        '...kkkk..kkkk...',
      ],
    },
    sage: {
      colors: { k: '#1a1626', G: '#8d88b8', F: '#e8c9a0', W: '#e8e4d8', R: '#6b5490', r: '#523c74', S: '#c49658' },
      map: [
        '.......kk.......',
        '......kGGk......',
        '.....kGGGGk.....',
        '....kGGGGGGk....',
        '....kFFFFFFk....',
        '....kFkFFkFk....',
        '...kWWWWWWWWk...',
        '...kWWWWWWWWkS..',
        '....kWWWWWWk.S..',
        '...kRRRWWRRRkS..',
        '...kRRRWWRRRkS..',
        '...kRrRRRRrRkS..',
        '..kRRRRRRRRRRkS.',
        '..kRrRRRRRRrRkS.',
        '..kRRRRRRRRRRkS.',
        '..kkkkkkkkkkkkS.',
      ],
    },
    kid: {
      colors: { k: '#1a1626', H: '#c45a2c', F: '#f2c9a0', A: '#c4a03c', L: '#5a6378', B: '#3f4657' },
      map: [
        '................',
        '................',
        '................',
        '................',
        '......kkkk......',
        '.....kHHHHk.....',
        '.....kFFFFk.....',
        '.....kFkkFk.....',
        '.....kFFFFk.....',
        '....kAAAAAAk....',
        '...kAFAAAAFAk...',
        '...kAAAAAAAAk...',
        '....kLLkkLLk....',
        '....kLLk.kLLk...',
        '....kBBk.kBBk...',
        '...kkkk..kkkk...',
      ],
    },
    bard: {
      colors: { k: '#1a1626', P: '#e05252', C: '#3a6b8a', F: '#f2c9a0', A: '#8a4a8a', a: '#6b3a6b', L: '#c49658', l: '#96702e' },
      map: [
        '.....P..........',
        '....kPkkkk......',
        '...kCCCCCCk.....',
        '....kFFFFFk.....',
        '....kFkFkFk.....',
        '....kFFFFFk.....',
        '...kAAAAAAAk....',
        '..kAAAAAAAAAk...',
        '..kAFAAAAAAAk...',
        '..kAAAAAAAkLLk..',
        '..kaAAAAAkLLLLk.',
        '...kAAAAAkLlLLk.',
        '...kaAAAAAkLLk..',
        '....kLLkkLLkk...',
        '....kLLk.kLLk...',
        '...kkkk..kkkk...',
      ],
    },

    // boss crown overlay (12x8), drawn on top of a boss sprite
    crown: {
      colors: { Y: '#ffd94a', y: '#d8a03c', R: '#e05252' },
      map: [
        'Y....Y.....Y',
        'YY..YYY...YY',
        'YYY.YYY..YYY',
        'YYYYYYYYYYYY',
        'yYYRYYYYRYYy',
        'yYYYYYYYYYYy',
        'yyyyyyyyyyyy',
        '............',
      ],
    },
    // Playtest round 5: the friend mark. The 🕊 emoji pip was mush at pip
    // size ("the dove is unrecognizable") — a pixel heart reads instantly,
    // drawn like the crown, with a shine pixel so it's never colour-alone.
    heart: {
      colors: { R: '#ff6b9d', r: '#d84a7e', W: '#ffd8e8' },
      map: [
        '.RR..RR.',
        'RWRRRRRR',
        'RWRRRRRR',
        'RRRRRRRR',
        '.rRRRRr.',
        '..rRRr..',
        '...rr...',
        '........',
      ],
    },

    // ===== Wave 9: "The Tending" (post-game practice) =====

    // a Daily Tangle / Spiral Stair "monster" — the game's oldest metaphor
    // (every monster IS a tangle, per the Study reveal), finally just
    // standing there looking like one: a small scribbled knot with a stray
    // loop at each end and two worried eyes peeking out.
    tangle: {
      colors: { k: '#241a2e', T: '#a89cc4', E: '#ffffff', e: '#241a2e' },
      map: [
        '................',
        '.....k....k.....',
        '....kTk..kTk....',
        '.....kTkkTk.....',
        '...kkTTTTTTkk...',
        '..kTTTTTTTTTTk..',
        '.kTTTEeTTEeTTTk.',
        '.kTTTTTTTTTTTTk.',
        '.kTTkkTTTTkkTTk.',
        '.kTTTTkkkkTTTTk.',
        '..kTTTTTTTTTTk..',
        '...kkTTTTTTkk...',
        '....kTk..kTk....',
        '.....k....k.....',
        '................',
        '................',
      ],
    },

    // castle furnishing (Wave 9, P3): each purchasable piece is TWO sprites
    // — an "empty" state (bare floor / dirt / frame) and a "bought" state —
    // so the purchase is visible at a glance, not just in a dialog. Rugs
    // reuse `hallFloor` for their empty state (there is nothing there yet
    // but floor); the rest get their own empty look.
    gardenEmpty: {
      colors: { A: '#8f819c', k: '#4a4458', d: '#6b4a34' },
      map: [
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAkkkkkkkkkkAAA',
        'AAkddddddddddkAA',
        'AAkdddddddddddkA',
        'AAkddddddddddkAA',
        'AAkdddddddddddkA',
        'AAkddddddddddkAA',
        'AAkdddddddddddkA',
        'AAkddddddddddkAA',
        'AAkkkkkkkkkkkkAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
      ],
    },
    gardenFull: {
      colors: { A: '#8f819c', k: '#4a4458', d: '#6b4a34', g: '#4e9e52', Y: '#ffd94a' },
      map: [
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAkkkkkkkkkkAAA',
        'AAkggYggggYggkAA',
        'AAkgYYgggYYgggkA',
        'AAkggggYgggggkAA',
        'AAkgYggggYgggdkA',
        'AAkggYgggggYgdkA',
        'AAkgggggYgggddkA',
        'AAkddddddddddkAA',
        'AAkkkkkkkkkkkkAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
      ],
    },
    shelfEmpty: {
      colors: { A: '#8f819c', k: '#5a4a34' },
      map: [
        'AAAAAAAAAAAAAAAA',
        'AAkkkkkkkkkkkkAA',
        'AAkAAAAAAAAAAkAA',
        'AAkAAAAAAAAAAkAA',
        'AAkkkkkkkkkkkkAA',
        'AAkAAAAAAAAAAkAA',
        'AAkAAAAAAAAAAkAA',
        'AAkkkkkkkkkkkkAA',
        'AAkAAAAAAAAAAkAA',
        'AAkAAAAAAAAAAkAA',
        'AAkkkkkkkkkkkkAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
      ],
    },
    shelfFull: {
      colors: { A: '#8f819c', k: '#5a4a34', R: '#c0504a', G: '#4e9e52', B: '#5a7ec4', Y: '#ffd94a' },
      map: [
        'AAAAAAAAAAAAAAAA',
        'AAkkkkkkkkkkkkAA',
        'AAkRGBYRGBYRGkAA',
        'AAkRGBYRGBYRGkAA',
        'AAkkkkkkkkkkkkAA',
        'AAkYBRGYBRGYBkAA',
        'AAkYBRGYBRGYBkAA',
        'AAkkkkkkkkkkkkAA',
        'AAkGRYBGRYBGRkAA',
        'AAkGRYBGRYBGRkAA',
        'AAkkkkkkkkkkkkAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
      ],
    },
    rugFull: {
      colors: { A: '#8f819c', k: '#4a4458', R: '#c0504a', Y: '#ffd94a' },
      map: [
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAkkkkkkkkkkkkAA',
        'AAkRRRRRRRRRRkAA',
        'AAkRYYYYYYYYRkAA',
        'AAkRYRRRRRRYRkAA',
        'AAkRYRYYYYRYRkAA',
        'AAkRYRYRRYRYRkAA',
        'AAkRYRYYYYRYRkAA',
        'AAkRYRRRRRRYRkAA',
        'AAkRYYYYYYYYRkAA',
        'AAkRRRRRRRRRRkAA',
        'AAkkkkkkkkkkkkAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
      ],
    },
    // one shared "statue" sprite for every commissioned-boss plinth (a
    // sculpted likeness of a specific boss is beyond this game's pixel
    // budget — the name lives in the bump dialog instead). The EMPTY
    // plinth reuses the Gallery's own `plinth` sprite — this room is a
    // museum too.
    statueFull: {
      colors: { A: '#8f819c', s: '#9a92b8', S: '#7a7098', p: '#6b6482', k: '#4a4458' },
      map: [
        'AAAAAAAAAAAAAAAA',
        'AAAAAAssSAAAAAAA',
        'AAAAAsSSssAAAAAA',
        'AAAAAsSSsSAAAAAA',
        'AAAAsSSSSSAAAAAA',
        'AAAAsSSSSSAAAAAA',
        'AAAAAsSSsAAAAAAA',
        'AAAAsSssSsAAAAAA',
        'AAAsSSSSSSsAAAAA',
        'AAAAAAppAAAAAAAA',
        'AAAkkkkkkkkkAAAA',
        'AAkppppppppkAAAA',
        'AAkppppppppkAAAA',
        'AAAkkkkkkkkkAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
      ],
    },
    // the pet's own little wardrobe — one static look; hats themselves are
    // drawn on the PET (an emoji overlay), not on this basket.
    petBasket: {
      colors: { A: '#8f819c', k: '#4a3424', w: '#a87a4a', R: '#c0504a' },
      map: [
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAkkkkkkkkAAAA',
        'AAAkRRRRRRRRkAAA',
        'AAAkRRRRRRRRkAAA',
        'AAAkwwwwwwwwkAAA',
        'AAAkwwwwwwwwkAAA',
        'AAAAkwwwwwwkAAAA',
        'AAAAAkkkkkkAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAA',
      ],
    },
    // the Spiral Stair's own tower, on the world map — castle-adjacent
    spiralTower: {
      colors: { g: '#4e9e52', k: '#3a2f4a', S: '#8f819c', s: '#6b6280', Y: '#ffd94a' },
      map: [
        'ggggggggggggggg',
        'ggggg.kkk.ggggg',
        'gggg.kSSSk.gggg',
        'ggg.kSsSsSk.ggg',
        'gg.kSsSSSsSk.gg',
        'g.kSsSSYSSsSk.g',
        '.kSsSSYYYSSsSk.',
        'kSsSSSYYYSSSsSk',
        'kSsSSSSYSSSSsSk',
        'kSSSssssssSSSSk',
        'kkSSSSSSSSSSkkk',
        'gkkSSSSSSSSkkgg',
        'ggkkkkkkkkkkggg',
        'gggggkkkkgggggg',
        'ggggggggggggggg',
        'ggggggggggggggg',
      ],
    },
  };

  // ---------- rendering ----------
  const cache = {};

  // Build (and cache) a canvas for a sprite at integer scale, with optional
  // palette overrides {char: hex} and horizontal mirroring.
  S.get = function (name, opts) {
    opts = opts || {};
    const scale = opts.scale || 3;
    const key = name + '|' + scale + '|' + (opts.mirror ? 'm' : '') + '|' + JSON.stringify(opts.palette || {});
    if (cache[key]) return cache[key];
    const def = S.DEFS[name];
    if (!def) throw new Error('unknown sprite: ' + name);
    const colors = Object.assign({}, def.colors, opts.palette || {});
    const h = def.map.length, w = def.map[0].length;
    const cv = document.createElement('canvas');
    cv.width = w * scale; cv.height = h * scale;
    const c = cv.getContext('2d');
    for (let y = 0; y < h; y++) {
      const row = def.map[y];
      for (let x = 0; x < w; x++) {
        const ch = row[x];
        if (ch === '.' || ch === undefined) continue;
        const col = colors[ch];
        if (!col) continue;
        const dx = opts.mirror ? (w - 1 - x) : x;
        c.fillStyle = col;
        c.fillRect(dx * scale, y * scale, scale, scale);
      }
    }
    cache[key] = cv;
    return cv;
  };

  // ---------- Wave 8b: the calmed look (P1) ----------
  // A befriended (or actively-being-soothed) monster renders in a SOFTENED
  // palette: every colour blended toward a warm white. One transform gives all
  // ~70 monster types their calmed look for free — no new sprite art.
  //
  // Three things this has to get right, all of them cache-related:
  //  1. It returns a COMPLETE {char: hex} palette, not a flag. S.get's cache key
  //     is `name|scale|mirror|JSON.stringify(palette)` — a flag on opts would
  //     NOT enter the key, so the first render would be cached and every later
  //     call (calm or not) would get that same canvas back. A materialized
  //     palette gets its own key for free.
  //  2. It blends EVERY key in the merged colour set, not just A/B — `skeleton`
  //     and `mage` have no A or B at all (they're W/w/E/R and H/h/S/s), so an
  //     A/B-only transform would silently no-op on two whole families.
  //  3. It emits keys in SORTED order, so the same monster always stringifies to
  //     the same cache key instead of quietly minting duplicate canvases.
  const SOFT_TARGET = [255, 244, 230];   // a warm white — calm, never washed-out grey
  function hexToRgb(h) {
    if (typeof h !== 'string') return null;
    const m = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(h.trim());
    if (!m) return null;
    let s = m[1];
    if (s.length === 3) s = s[0] + s[0] + s[1] + s[1] + s[2] + s[2];
    return [parseInt(s.slice(0, 2), 16), parseInt(s.slice(2, 4), 16), parseInt(s.slice(4, 6), 16)];
  }
  const hex2 = n => Math.max(0, Math.min(255, Math.round(n))).toString(16).padStart(2, '0');

  // amount 0 = untouched, 1 = fully warm white. 0.45 is the calmed default.
  S.softPalette = function (name, palette, amount) {
    const def = S.DEFS[name];
    if (!def) return Object.assign({}, palette || {});
    const a = amount == null ? 0.45 : amount;
    const merged = Object.assign({}, def.colors, palette || {});
    const out = {};
    for (const ch of Object.keys(merged).sort()) {   // sorted => stable cache key
      const rgb = hexToRgb(merged[ch]);
      if (!rgb) { out[ch] = merged[ch]; continue; }  // pass through anything odd untouched
      out[ch] = '#' + rgb.map((v, i) => hex2(v + (SOFT_TARGET[i] - v) * a)).join('');
    }
    return out;
  };

  // Validate all sprite maps (row lengths + unknown chars). Returns list of problems.
  S.validate = function () {
    const problems = [];
    for (const [name, def] of Object.entries(S.DEFS)) {
      const w = def.map[0].length;
      def.map.forEach((row, i) => {
        if (row.length !== w) problems.push(`${name} row ${i}: length ${row.length} != ${w}`);
        for (const ch of row) {
          if (ch !== '.' && !def.colors[ch]) problems.push(`${name} row ${i}: unknown char "${ch}"`);
        }
      });
    }
    return problems;
  };
})();
