// MathMaker v2 — original pixel-art sprites, authored as character maps.
// Each sprite is 16x16 (unless noted); chars map to colors, '.' = transparent.
// Rendered once to offscreen canvases and cached per (sprite, palette, scale).
var MM = globalThis.MM = globalThis.MM || {};
(function () {
  'use strict';

  const S = MM.sprites = {};

  // ---------- sprite definitions ----------
  // colors: char -> hex. Palette swaps override these per monster variant.
  S.DEFS = {

    // ===== terrain =====
    grass: {
      colors: { G: '#4e9e52', g: '#3f8746', L: '#63b167' },
      map: [
        'GGGGGGGGGGGGGGGG',
        'GGGGgGGGGGGGLGGG',
        'GGGGGGGGGGGGGGGG',
        'GLGGGGGGgGGGGGGG',
        'GGGGGGGGGGGGGGgG',
        'GGGGGGGGGGGGGGGG',
        'GGgGGGGGGGGLGGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGGGLGGGGGGGGG',
        'GGGGGGGGGGGGGgGG',
        'GgGGGGGGGGGGGGGG',
        'GGGGGGGGgGGGGGGG',
        'GGGGLGGGGGGGGGGG',
        'GGGGGGGGGGGGLGGG',
        'GGGGGGgGGGGGGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    grass2: {
      colors: { G: '#4a9a4e', g: '#3f8746', L: '#63b167' },
      map: [
        'GGGGGGGGGGGGGGGG',
        'GGGGGGGGgGGGGGGG',
        'GGLGGGGGGGGGGGGG',
        'GGGGGGGGGGGGgGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGGgGGGGLGGGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGLG',
        'GgGGGGGGGGGGGGGG',
        'GGGGGGGGLGGGGGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGgGGGGGGGgGGG',
        'GGGGGGGGGGGGGGGG',
        'GLGGGGGGGGGGGGGG',
        'GGGGGGGGGgGGGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    tree: {
      colors: { G: '#4e9e52', g: '#3f8746', T: '#2c6b34', t: '#3d8544', d: '#1f4f26', B: '#6b4a2f', b: '#52381f' },
      map: [
        'GGGGGttTTtGGGGGG',
        'GGGtTTTTTTTtGGGG',
        'GGtTTtTTTTTTtGGG',
        'GtTTTTTTtTTTTtGG',
        'GtTTtTTTTTTdTtGG',
        'tTTTTTTtTTTTTTtG',
        'tTTdTTTTTTtTTTtG',
        'tTTTTTtTTTTTdTtG',
        'GtTTTTTTdTTTTtGG',
        'GGtdTTTTTTTtTGGG',
        'GGGtTTdTTTtTtGGG',
        'GGGGGtBBbtGGGGGG',
        'GGGGGGBBbGGGGGGG',
        'GGGGGGBBbGGGGGGG',
        'GGGGgGBBbGGgGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    water: {
      colors: { W: '#2f6fc4', w: '#5d97e0', d: '#255a9e' },
      map: [
        'WWWWWWWWWWWWWWWW',
        'WWwwWWWWWWWWWWWW',
        'WWWWWWWWWwwwWWWW',
        'WWWWWWWWWWWWWWWW',
        'WdWWWWWWWWWWWWdW',
        'WWWWWwwWWWWWWWWW',
        'WWWWWWWWWWWWWWWW',
        'WWWWWWWWWWwwWWWW',
        'WwwWWWWWWWWWWWWW',
        'WWWWWWWdWWWWWWWW',
        'WWWWWWWWWWWWWwwW',
        'WWWWwwWWWWWWWWWW',
        'WWWWWWWWWWWWWWWW',
        'WWWWWWWWWwWWWWWW',
        'WWdWWWWWWWWWWWWW',
        'WWWWWWWWWWWWWWWW',
      ],
    },
    water2: {
      colors: { W: '#2f6fc4', w: '#5d97e0', d: '#255a9e' },
      map: [
        'WWWWWWWWWWWWWWWW',
        'WWWWWWWWWwwWWWWW',
        'WWwwWWWWWWWWWWWW',
        'WWWWWWWWWWWWWWWW',
        'WWWWWWWWWWWWWdWW',
        'WWWWWWWwwWWWWWWW',
        'WdWWWWWWWWWWWWWW',
        'WWWWWWWWWWWWwwWW',
        'WWWWwwWWWWWWWWWW',
        'WWWWWWWWWdWWWWWW',
        'WwwWWWWWWWWWWWWW',
        'WWWWWWwwWWWWWWWW',
        'WWWWWWWWWWWWWWWW',
        'WWWwWWWWWWWwWWWW',
        'WWWWWWWWdWWWWWWW',
        'WWWWWWWWWWWWWWWW',
      ],
    },
    mountain: {
      colors: { G: '#4e9e52', M: '#8a8578', m: '#5f5b50', S: '#eceade', k: '#3e3b33' },
      map: [
        'GGGGGGGSGGGGGGGG',
        'GGGGGGSSSGGGGGGG',
        'GGGGGSSSSMGGGGGG',
        'GGGGGSMMMMmGGGGG',
        'GGGGMMMMMMmmGGGG',
        'GGGMMMmMMMMmmGGG',
        'GGGMMMMMMmMMmGGG',
        'GGMMMmMMMMMMmmGG',
        'GGMMMMMMmMMMMmGG',
        'GMMMmMMMMMMMmmmG',
        'GMMMMMMMMmMMMMmG',
        'MMMmMMMmMMMMmmmm',
        'MMMMMMMMMMMmMMmm',
        'kMkkMMkMMkkMMkkm',
        'GkGGkkGkkGGkkGGk',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    wall: {
      colors: { K: '#4a4258', k: '#332c44', h: '#5c5470' },
      map: [
        'KKKKKKKkKKKKKKKK',
        'KhKKKKKkKKKKhKKK',
        'KKKKKKKkKKKKKKKK',
        'kkkkkkkkkkkkkkkk',
        'KKKkKKKKKKKkKKKK',
        'KKKkKKhKKKKkKKKK',
        'KKKkKKKKKKKkKKKK',
        'kkkkkkkkkkkkkkkk',
        'KKKKKKKkKKKKKKKK',
        'KhKKKKKkKKKKKhKK',
        'KKKKKKKkKKKKKKKK',
        'kkkkkkkkkkkkkkkk',
        'KKKkKKKKKKKkKKKK',
        'KKKkKKKKhKKkKKKK',
        'KKKkKKKKKKKkKKKK',
        'kkkkkkkkkkkkkkkk',
      ],
    },
    floor: {
      colors: { F: '#57506a', f: '#4a445c', d: '#3f394f' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFfFFFFFFFFFFF',
        'FFFFFFFFFFFdFFFF',
        'FFFFFFFFFFFFFFFF',
        'FdFFFFFfFFFFFFFF',
        'FFFFFFFFFFFFFFfF',
        'FFFFFFFFFFFFFFFF',
        'FFFfFFFFFFdFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFFFFFdFFFFFFfFF',
        'FfFFFFFFFFFFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFFFFFFFfFFFFdFF',
        'FFdFFFFFFFFFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFFFFfFFFFFFFFFF',
      ],
    },
    doorMagic: {
      colors: { K: '#4a4258', k: '#332c44', D: '#6b4fc0', d: '#523a99', Y: '#ffd94a', h: '#8d75d8' },
      map: [
        'KKKKKKKKKKKKKKKK',
        'KKKKkkkkkkkkKKKK',
        'KKKkDDDDDDDDkKKK',
        'KKkDDhDDDDhDDkKK',
        'KKkDDDDDDDDDDkKK',
        'KKkDDDYYYYDDDkKK',
        'KKkDDYYddYYDDkKK',
        'KKkDDYdDDdYDDkKK',
        'KKkDDYYddYYDDkKK',
        'KKkDDDYYYYDDDkKK',
        'KKkDDDDDDDDDDkKK',
        'KKkDDhDDDDhDDkKK',
        'KKkDDDDDDDDDDkKK',
        'KKkDDDDDDDDDDkKK',
        'KKkDDDDDDDDDDkKK',
        'kkkkkkkkkkkkkkkk',
      ],
    },
    chest: {
      colors: { F: '#57506a', f: '#4a445c', C: '#b0763e', c: '#8a5a2c', k: '#5f3d1c', Y: '#ffd94a', y: '#d8a03c' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFFkkkkkkkkkkFFF',
        'FFkCCCCCCCCCCkFF',
        'FkCCcCCCCCCcCCkF',
        'FkCCCCYYYYCCCCkF',
        'FkkkkkkkkkkkkkkF',
        'FkCCCCYyyYCCCCkF',
        'FkCCCCyYYyCCCCkF',
        'FkCcCCYyyYCCcCkF',
        'FkCCCCCCCCCCCCkF',
        'FkCcCCCCCCCcCCkF',
        'FFkkkkkkkkkkkkFF',
        'FFFFFFFFFFFFFFFF',
        'FFFFfFFFFFFfFFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    ladder: {
      colors: { F: '#57506a', f: '#4a445c', L: '#c49658', l: '#96702e', d: '#2a2438' },
      map: [
        'FFFddddddddddFFF',
        'FFdLddddddddLdFF',
        'FFdLddddddddLdFF',
        'FFdLLLLLLLLLLdFF',
        'FFdLddddddddLdFF',
        'FFdLddddddddLdFF',
        'FFdLLLLLLLLLLdFF',
        'FFdLddddddddLdFF',
        'FFdLddddddddLdFF',
        'FFdLLLLLLLLLLdFF',
        'FFdLddddddddLdFF',
        'FFdLddddddddLdFF',
        'FFdLLLLLLLLLLdFF',
        'FFdlddddddddldFF',
        'FFdlddddddddldFF',
        'FFFddddddddddFFF',
      ],
    },
    castle: {
      colors: { G: '#4e9e52', S: '#b4b2c8', s: '#8d8ba4', k: '#5c5a72', R: '#e05252', d: '#2a2438', Y: '#ffd94a' },
      map: [
        'GGGRGGGGGGGGRGGG',
        'GGGRRGGGGGGGRRGG',
        'GGGSGGGGGGGGSGGG',
        'GGSSSGSSSSGSSSGG',
        'GGSkSSSkkSSSkSGG',
        'GGSSSSSSSSSSSSGG',
        'GGSsSSsSSsSSsSGG',
        'GGSSSSSSSSSSSSGG',
        'GSSSSSSSSSSSSSSG',
        'GSsSSkddkSSSSsSG',
        'GSSSkddddkSSSSSG',
        'GSsSkddddkSSsSSG',
        'GSSSkddddkSSSSSG',
        'GSSSkdYddkSSSSSG',
        'GSSSkddddkSSSSSG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    murk: { // the Murk: fog that grew where light stopped reaching
      colors: { D: '#3a3f4d', d: '#2e3340', g: '#4a5063', h: '#585f75' },
      map: [
        'DDDdddDDDDddDDDD',
        'DdggDDDDggDDDDdD',
        'DghhgDDghhgDDDDD',
        'DDgggDDDgggDDdDD',
        'dDDDDdDDDDDghgDD',
        'DDghgDDDDdDgggDD',
        'DghhhgDDDDDDDDDd',
        'DDggggDDghgDDDDD',
        'dDDDDDDghhhgDDDD',
        'DDDdDDDDgggDDdDD',
        'DghgDDdDDDDDDDDD',
        'DgggDDDDDghgDDdD',
        'DDDDdDDDghhhgDDD',
        'dDDDDDDDDgggDDDD',
        'DDdDDghgDDDDDdDD',
        'DDDDDgggDDDDDDDD',
      ],
    },
    lighthouse: { // the Great Lighthouse, dark as a closed eye
      colors: { G: '#4e9e52', W: '#d8d4c8', w: '#aca89c', R: '#8a3d3d', r: '#6b2e2e', d: '#2a2438', k: '#5c5a72' },
      map: [
        'GGGGGGdddGGGGGGG',
        'GGGGGdkdkdGGGGGG',
        'GGGGGdddddGGGGGG',
        'GGGGGRRRRRGGGGGG',
        'GGGGGrRRRrGGGGGG',
        'GGGGGWWWWWGGGGGG',
        'GGGGGWwWWWGGGGGG',
        'GGGGGRRRRRGGGGGG',
        'GGGGGrRRRrGGGGGG',
        'GGGGGWWWWWGGGGGG',
        'GGGGWWwWWWWGGGGG',
        'GGGGWWWWwWWGGGGG',
        'GGGGRRRRRRRGGGGG',
        'GGGGrRRRRRrGGGGG',
        'GGGwwWWWWWwwGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    petPup: { // the Compass Pup (blue egg)
      colors: { B: '#a8794a', b: '#8a5f38', W: '#f2ede4', k: '#1a1626', N: '#3d2c1e', R: '#e05252' },
      map: [
        '............',
        '.bb......bb.',
        '.bBb....bBb.',
        '.bBBbbbbBBb.',
        '.bBBBBBBBBb.',
        '.bBkBBBBkBb.',
        '.bBBBNNBBBb.',
        '..bBBNNBBb..',
        '..bBBBBBBbb.',
        '.bBBBBBBBBb.',
        '.bBb.bb.bBb.',
        '............',
      ],
    },
    petCat: { // the Sprout Cat (green egg)
      colors: { B: '#6fae62', b: '#54874a', W: '#e4f2dc', k: '#1a1626', P: '#e08ab0', L: '#3d6b34' },
      map: [
        '..L.........',
        '..Lb.....b..',
        '.bBBb...bBb.',
        '.bBBBbbbBBb.',
        '.bBBBBBBBBb.',
        '.bBkBBBBkBb.',
        '.bBBBPPBBBb.',
        '..bBBBBBBb..',
        '..bBBBBBBb..',
        '.bBBBBBBBBbb',
        '.bBb.bb.bBb.',
        '............',
      ],
    },
    petNewt: { // the Ember Newt (rose egg)
      colors: { B: '#e0854a', b: '#b8642f', W: '#f9e0c8', k: '#1a1626', Y: '#ffd94a', R: '#c23c2c' },
      map: [
        '............',
        '.....YY.....',
        '....bYYb....',
        '...bBBBBb...',
        '..bBBBBBBb..',
        '..bBkBBkBb..',
        '..bBBBBBBb..',
        '..bBWWWWBb..',
        '..bBBBBBBbb.',
        '.bBBb..bBBbb',
        '.bb......bbb',
        '............',
      ],
    },
    chute: { // a drop chute: dark, deep, and strictly one-way
      colors: { F: '#57506a', f: '#4a445c', d: '#241f36', e: '#12101c', B: '#6b4522', Y: '#ffd94a' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FfFFFFFFFFFFFfFF',
        'FFBBBBBBBBBBBBFF',
        'FFBddddddddddBFF',
        'FFBddeeeeeeddBFF',
        'FFBdeeeeeeeedBFF',
        'FFBdeeYeeYeedBFF',
        'FFBdeeeYYeeedBFF',
        'FFBdeeeYYeeedBFF',
        'FFBdeeYeeYeedBFF',
        'FFBdeeeeeeeedBFF',
        'FFBddeeeeeeddBFF',
        'FFBddddddddddBFF',
        'FFBBBBBBBBBBBBFF',
        'FfFFFFFFFFFFFFfF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    ship: { // the Compass Rose under sail (for the voyage scene)
      colors: { W: '#f2ede4', w: '#d8cdb4', B: '#8a5a2c', b: '#6b4522', k: '#523618', R: '#e05252' },
      map: [
        '.......k........',
        '.......kWW......',
        '.......kWWWW....',
        '.......kWWWWWW..',
        '..WWWWWkWWWWW...',
        '...WWWWkWWW.....',
        '.....WWkW.......',
        '.......k....R...',
        '.......k........',
        '.bBBBBBBBBBBBb..',
        '..bBBBBBBBBBb...',
        '...bbBBBBBbb....',
        '................',
        '................',
        '................',
        '................',
      ],
    },
    pier: { // wooden pier reaching into the western sea
      colors: { G: '#4e9e52', W: '#3d6b8a', w: '#2c5068', B: '#8a5a2c', b: '#6b4522', k: '#523618' },
      map: [
        'WWWWWWWWWWWWWWWW',
        'WWwWWBBBBBBWWwWW',
        'WWWWWBbBbBBWWWWW',
        'WwWWWBBBBbBWWWWW',
        'WWWWkBbBBBBkWWwW',
        'WWWWkBBBbBBkWWWW',
        'WwWWWBBBBBBWWWWW',
        'WWWWWBbBBbBWwWWW',
        'WWWWkBBBBBBkWWWW',
        'WWwWkBBbBBBkWWwW',
        'GGGGGBBBBbBGGGGG',
        'GGGGGBbBBBBGGGGG',
        'GGGGGBBBBBBGGGGG',
        'GGGGGGBBBBGGGGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    wallCrack: { // a wall with a hairline crack — worth a nudge
      colors: { K: '#4a4258', k: '#332c44', h: '#5c5470', c: '#6e6488' },
      map: [
        'KKKKKKKkKKKKKKKK',
        'KhKKKKKkKKKKhKKK',
        'KKKKKKKcKKKKKKKK',
        'kkkkkkkckkkkkkkk',
        'KKKkKKKcKKKkKKKK',
        'KKKkKKcKKKKkKKKK',
        'KKKkKKcKKKKkKKKK',
        'kkkkkkckkkkkkkkk',
        'KKKKKKcKKKKKKKKK',
        'KhKKKKKcKKKKKhKK',
        'KKKKKKKcKKKKKKKK',
        'kkkkkkkckkkkkkkk',
        'KKKkKKKKcKKkKKKK',
        'KKKkKKKKcKKkKKKK',
        'KKKkKKKKcKKkKKKK',
        'kkkkkkkkckkkkkkk',
      ],
    },
    pool: { // a glinting tide pool set into the cave floor
      colors: { F: '#57506a', f: '#4a445c', W: '#2c8a8a', w: '#1d6468', s: '#7ee0d4' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFfwwwwwFFFFFF',
        'FFFwwWWWWwwwFFFF',
        'FFwWWWWsWWWWwFFF',
        'FfwWWsWWWWWWwwFF',
        'FwWWWWWWWWsWWwFF',
        'FwWWsWWWWWWWWwFF',
        'FwWWWWWWsWWWWwFF',
        'FFwWWWWWWWWWwfFF',
        'FFwWsWWWWsWWwFFF',
        'FFFwwWWWWWwwFFFF',
        'FFFFwwWWwwwFFFFF',
        'FFFFFfwwwFFFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFdFFFFFFFFfFFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    urchin: { // spiny urchins carpeting the floor: crossing stings
      colors: { F: '#57506a', f: '#4a445c', U: '#2b1a33', u: '#4a2c5c', p: '#8a5ca8' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFuFFFFFFFuFFFFF',
        'FuUUuFFFFuUUuFFF',
        'FUUpUUFFuUUUUuFF',
        'FuUUUuFFFuUpUFFF',
        'FFuUuFFFFFuUuFFF',
        'FFFuFFFFFFFuFFFF',
        'FFFFFFuFFFFFFFFF',
        'FFFFFuUuFFFFFFFF',
        'FFFFuUUUuFFFuFFF',
        'FFFFuUpUuFFuUuFF',
        'FFFFFuUuFFuUUUuF',
        'FFFFFFuFFFuUpUuF',
        'FFFFFFFFFFFuUuFF',
        'FFfFFFFFFFFFuFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    slick: { // slick wet rock: step on and you skid
      colors: { F: '#57506a', S: '#6ea8b8', s: '#578a9c', h: '#a8dce8' },
      map: [
        'SSSSSSSSSSSSSSSS',
        'SShSSSSSsSSSSSSS',
        'SSShhSSSSSSShSSS',
        'SSSSSSSSSShhSSSS',
        'SsSSSShhSSSSSSSS',
        'SSSSShhSSSSSSsSS',
        'SSSSSSSSSSSSSSSS',
        'SShSSSSSShhSSSSS',
        'SSShhSSSSSShSSSS',
        'SSSSSSsSSSSSSSSS',
        'SsSSSSSSSSSShhSS',
        'SSSSShSSSSShSSSS',
        'SSSShhSSSSSSSSsS',
        'SSSSSSSSsSSSSSSS',
        'SSsSSSSSSSShSSSS',
        'SSSSSSSSSSSSSSSS',
      ],
    },
    pad: { // a glowing tide pad: stand on it and whoosh
      colors: { F: '#57506a', f: '#4a445c', R: '#5ee8c8', r: '#2c8a7a', d: '#1d5a50' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFFrRRRRrFFFFF',
        'FFFrRRrrrrRRrFFF',
        'FFrRrfFFFFfrRrFF',
        'FrRrFFFFFFFFrRrF',
        'FrRfFFrRRrFFfRrF',
        'FRrFFrRddRrFFrRF',
        'FRrFFRdFFdRFFrRF',
        'FRrFFRdFFdRFFrRF',
        'FRrFFrRddRrFFrRF',
        'FrRfFFrRRrFFfRrF',
        'FrRrFFFFFFFFrRrF',
        'FFrRrfFFFFfrRrFF',
        'FFFrRRrrrrRRrFFF',
        'FFFFFrRRRRrFFFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    keyTile: { // a key, just lying there. Suspiciously convenient.
      colors: { F: '#57506a', f: '#4a445c', Y: '#ffd94a', y: '#d8a03c', k: '#8a6a1c' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFFFFFFFFFFFFFFF',
        'FFFYYYFFFFFFFFFF',
        'FFYykyYFFFFFFFFF',
        'FFYkFkYFFFFFFFFF',
        'FFYykyYFFFFFFFFF',
        'FFFYYYyFFFFFFFFF',
        'FFFFFyYyFFFFFFFF',
        'FFFFFFyYyFFFFFFF',
        'FFFFFFFyYyYFFFFF',
        'FFFFFFFFyYyYFFFF',
        'FFFFFFFFFyYFYFFF',
        'FFFFFFFFFFFFFFFF',
        'FFfFFFFFFFFdFFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    lockDoor: { // an iron-banded door with a big golden lock
      colors: { K: '#4a4258', k: '#332c44', D: '#6e5a8a', d: '#574570', Y: '#ffd94a', y: '#8a6a1c' },
      map: [
        'KKKKKKKKKKKKKKKK',
        'KKKKkkkkkkkkKKKK',
        'KKKkDDDDDDDDkKKK',
        'KKkDDdDDDDdDDkKK',
        'KKkDDDDDDDDDDkKK',
        'KKkddddddddddkKK',
        'KKkDDDDDDDDDDkKK',
        'KKkDDDYYYYDDDkKK',
        'KKkDDYYyyYYDDkKK',
        'KKkDDYyyyyYDDkKK',
        'KKkDDYYyyYYDDkKK',
        'KKkDDDYyyYDDDkKK',
        'KKkddddddddddkKK',
        'KKkDDdDDDDdDDkKK',
        'KKkDDDDDDDDDDkKK',
        'kkkkkkkkkkkkkkkk',
      ],
    },
    lever: { // an old stone-set lever, begging to be pulled
      colors: { F: '#57506a', f: '#4a445c', S: '#8d8ba4', s: '#5c5a72', B: '#8a5a2c', Y: '#ffd94a' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FFFFFFFFFFYFFFFF',
        'FFFFFFFFFYYYFFFF',
        'FFFFFFFFFFYFFFFF',
        'FFFFFFFFFBFFFFFF',
        'FFFFFFFFBBFFFFFF',
        'FFFFFFFBBFFFFFFF',
        'FFFFFFBBFFFFFFFF',
        'FFFFFBBFFFFFFFFF',
        'FFFFsSSsFFFFFFFF',
        'FFFsSSSSsFFFFFFF',
        'FFsSSssSSsFFFFFF',
        'FFsSSSSSSsFFFFFF',
        'FFssssssssFFFFFF',
        'FFfFFFFFFFFfFFFF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    gate: { // heavy stone bars: some lever, somewhere, moves them
      colors: { F: '#57506a', S: '#8d8ba4', s: '#5c5a72', k: '#332c44' },
      map: [
        'ssssssssssssssss',
        'sSSskSSskSSskSSs',
        'sSSskSSskSSskSSs',
        'sSsskSsskSsskSss',
        'sSSskSSskSSskSSs',
        'sSSskSSskSSskSSs',
        'ssssssssssssssss',
        'sSSskSSskSSskSSs',
        'sSsskSsskSsskSss',
        'sSSskSSskSSskSSs',
        'sSSskSSskSSskSSs',
        'ssssssssssssssss',
        'sSSskSSskSSskSSs',
        'sSSskSsskSSskSss',
        'sSSskSSskSSskSSs',
        'ssssssssssssssss',
      ],
    },
    stairsDown: { // steps descending into the dark
      colors: { F: '#57506a', f: '#4a445c', d: '#2a2438', e: '#1a1626' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FffffffffffffffF',
        'FfFFFFFFFFFFFFfF',
        'FfFddddddddddFfF',
        'FfFdffffffffdFfF',
        'FfFdfddddddfdFfF',
        'FfFdfdeeeedfdFfF',
        'FfFdfdeeeedfdFfF',
        'FfFdfdeeeedfdFfF',
        'FfFdfdeeeedfdFfF',
        'FfFdfddddddfdFfF',
        'FfFdffffffffdFfF',
        'FfFddddddddddFfF',
        'FfFFFFFFFFFFFFfF',
        'FffffffffffffffF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    stairsUp: { // steps climbing back toward daylight
      colors: { F: '#57506a', f: '#4a445c', L: '#8d8ba4', l: '#6e6c84', Y: '#c4c2d8' },
      map: [
        'FFFFFFFFFFFFFFFF',
        'FffffffffffffffF',
        'FfYYYYYYYYYYYYfF',
        'FfYLLLLLLLLLLYfF',
        'FfYLllllllllLYfF',
        'FfYLlLLLLLLlLYfF',
        'FfYLlLllllLlLYfF',
        'FfYLlLlffLLlLYfF',
        'FfYLlLlffLLlLYfF',
        'FfYLlLllllLlLYfF',
        'FfYLlLLLLLLlLYfF',
        'FfYLllllllllLYfF',
        'FfYLLLLLLLLLLYfF',
        'FfYYYYYYYYYYYYfF',
        'FffffffffffffffF',
        'FFFFFFFFFFFFFFFF',
      ],
    },
    board: { // the notice board: planks, pinned paper notices, sturdy legs
      colors: { G: '#4e9e52', B: '#8a5a2c', b: '#6b4522', W: '#f2ede4', w: '#d8cdb4', Y: '#ffd94a', R: '#e05252' },
      map: [
        'GGGGGGGGGGGGGGGG',
        'GGBBBBBBBBBBBBGG',
        'GGBbbbbbbbbbbBGG',
        'GGBbWWwbbWWWbBGG',
        'GGBbWwWbRWwWbBGG',
        'GGBbWWWbbWWwbBGG',
        'GGBbwWWbbwWWbBGG',
        'GGBbbbbbbbbbbBGG',
        'GGBbWWWwbYYwbBGG',
        'GGBbWwWWbbbbbBGG',
        'GGBbbbbbbbbbbBGG',
        'GGBBBBBBBBBBBBGG',
        'GGGGBBGGGGBBGGGG',
        'GGGGBBGGGGBBGGGG',
        'GGGGBBGGGGBBGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    shop: {
      colors: { G: '#4e9e52', R: '#e05252', W: '#f2ede4', B: '#8a5a2c', b: '#6b4522', d: '#2a2438', Y: '#ffd94a' },
      map: [
        'GGGGGGGGGGGGGGGG',
        'GGRWRWRWRWRWRGGG',
        'GRWRWRWRWRWRWRGG',
        'GRRRRRRRRRRRRRGG',
        'GGBGGGGGGGGGBGGG',
        'GGBGGGGGGGGGBGGG',
        'GGBGYGGGGGGGBGGG',
        'GGBBBBBBBBBBBGGG',
        'GGBbbBbbBbbBBGGG',
        'GGBBBBBBBBBBBGGG',
        'GGBbbBddbBbbBGGG',
        'GGBBBBddbBBBBGGG',
        'GGBbbBddbBbbBGGG',
        'GGBBBBBBBBBBBGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    inn: {
      colors: { G: '#4e9e52', R: '#c05a3c', r: '#96432a', W: '#efe6d4', w: '#d8cdb4', d: '#2a2438', Y: '#ffd94a', k: '#5c4a38' },
      map: [
        'GGGGGGGGGGGGGGGG',
        'GGGGGGRRGGGGGGGG',
        'GGGGRRRRRRGGGGGG',
        'GGGRRrRRRRRGGGGG',
        'GGRRRRRRrRRRGGGG',
        'GRRrRRRRRRRRRGGG',
        'GRRRRRRRRrRRRGGG',
        'GGWWWWWWWWWWGGGG',
        'GGWwWWYYWWwWGGGG',
        'GGWWWWYYWWWWGGGG',
        'GGWwWWWWWWwWGGGG',
        'GGWWWddWWWWWGGGG',
        'GGWwWddWWkkWGGGG',
        'GGWWWddWWkkWGGGG',
        'GGWWWddWWWWWGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },
    hole: {
      colors: { G: '#4e9e52', g: '#3f8746', d: '#1c1830', D: '#2c2544', m: '#3a3354' },
      map: [
        'GGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGgddddddgGGGG',
        'GGGddddddddddGGG',
        'GGddDDddddDDddGG',
        'GGdDdddddddddDGG',
        'GdddddddddddddgG',
        'GddddddddddddddG',
        'GddddddddddddddG',
        'GdddddddddddddGG',
        'GGddddddddddddGG',
        'GGmddddddddddGGG',
        'GGGmmddddddmGGGG',
        'GGGGGmmmmmmGGGGG',
        'GGGGGGGGGGGGGGGG',
        'GGGGGGGGGGGGGGGG',
      ],
    },

    // ===== the hero (a proper knight!) =====
    hero: {
      colors: {
        k: '#1a1626', P: '#e05252', H: '#c4d0e4', h: '#8b97b0', F: '#f2c9a0',
        A: '#9aa6c0', a: '#6e7a96', L: '#5a6378', B: '#3f4657', W: '#eef2fa',
        G: '#d8a03c',
      },
      map: [
        '......PP........',
        '.....PPPP.......',
        '....kHHHHk......',
        '...kHHHHHHk.....',
        '...kHhFFhHk.....',
        '...kHFFFFHk..W..',
        '....kHHHHk...W..',
        '...kAAAAAAk..W..',
        '..kAAAAAAAAk.W..',
        '..kaAAAAAAGGGW..',
        '..kaAAAAAAkGG...',
        '...kAAAAAAk.....',
        '...kLLLLLLk.....',
        '...kLLkkLLk.....',
        '...kBBk.kBBk....',
        '..kkkk..kkkk....',
      ],
    },
    hero2: {
      colors: {
        k: '#1a1626', P: '#e05252', H: '#c4d0e4', h: '#8b97b0', F: '#f2c9a0',
        A: '#9aa6c0', a: '#6e7a96', L: '#5a6378', B: '#3f4657', W: '#eef2fa',
        G: '#d8a03c',
      },
      map: [
        '......PP........',
        '.....PPPP.......',
        '....kHHHHk......',
        '...kHHHHHHk.....',
        '...kHhFFhHk.....',
        '...kHFFFFHk..W..',
        '....kHHHHk...W..',
        '...kAAAAAAk..W..',
        '..kAAAAAAAAk.W..',
        '..kaAAAAAAGGGW..',
        '..kaAAAAAAkGG...',
        '...kAAAAAAk.....',
        '...kLLLLLLk.....',
        '....kLLLLk......',
        '....kBBBBk......',
        '....kkkkkk......',
      ],
    },

    // ===== monsters (palette-swapped per dungeon) =====
    slime: {
      colors: { k: '#143318', A: '#52c45a', B: '#3a9642', W: '#a5e8a9', E: '#ffffff', e: '#1a1626', M: '#2c7534' },
      map: [
        '................',
        '................',
        '......kkkk......',
        '....kkAAAAkk....',
        '...kAAWWAAAAk...',
        '..kAWWAAAAAAAk..',
        '..kAWAAAAAAAAk..',
        '.kAAAAAAAAAAAAk.',
        '.kAAEeAAAAEeAAk.',
        'kAAAEeAAAAEeAAAk',
        'kAAAAAAAAAAAAAAk',
        'kAAAAMMMMMMAAAAk',
        'kAABAAMMMMAABAAk',
        'kBAABBAAAABBAABk',
        '.kkBBBBBBBBBBkk.',
        '...kkkkkkkkkk...',
      ],
    },
    rat: {
      colors: { k: '#241a14', A: '#8a7466', B: '#6b584c', E: '#e05252', F: '#d8b8a8', T: '#c49688', W: '#f2ede4' },
      map: [
        '................',
        '................',
        '....kk....kk....',
        '...kFFk..kFFk...',
        '...kFFFkkFFFk...',
        '....kAAAAAAk....',
        '...kAAAAAAAAk...',
        '..kAAEkAAkEAAk..',
        '..kAAAAAAAAAAk..',
        '.kAAAAAkkAAAAAk.',
        '.kAAAAAAAAAAAkT.',
        '.kBAAAAAAAABkTT.',
        '.kABAAAAAABAkT..',
        '..kAAWWWWAAkT...',
        '...kkWkkWkkT....',
        '....kk..kk......',
      ],
    },
    bat: {
      colors: { k: '#1c1428', A: '#6b5490', B: '#523c74', E: '#ffd94a', W: '#f2ede4', m: '#3f2c5c' },
      map: [
        '................',
        '.kk..........kk.',
        'kAAk........kAAk',
        'kAAAk......kAAAk',
        'kAAAAk.kk.kAAAAk',
        'kAmAAkkAAkkAAmAk',
        'kAAAAAAAAAAAAAAk',
        '.kAAAkAAAAkAAAk.',
        '.kAmAAEkkEAAmAk.',
        '..kAAAAAAAAAAk..',
        '..kAAkWAAWkAAk..',
        '...kAAkWWkAAk...',
        '....kAAAAAAk....',
        '.....kAAAAk.....',
        '......kkkk......',
        '................',
      ],
    },
    spider: {
      colors: { k: '#181420', A: '#4a3f5c', B: '#382f47', E: '#e05252', L: '#2c2438', W: '#8d80a4' },
      map: [
        '................',
        '.L....L..L....L.',
        '.L...L....L...L.',
        '..L..L....L..L..',
        '..L.kkkkkkkk.L..',
        '...kAAAAAAAAk...',
        'LLLkAWAAAAWAkLLL',
        '..kAAAAAAAAAAk..',
        '..kAEkAAAAkEAk..',
        'LLkAAEkAAkEAAkLL',
        '..kAAAAAAAAAAk..',
        '.L.kABAABAABk.L.',
        '.L..kkkkkkkk..L.',
        '.L..L......L..L.',
        'L...L......L...L',
        '................',
      ],
    },
    skeleton: {
      colors: { k: '#1a1626', W: '#e8e4d8', w: '#c4bfa8', E: '#52c4c4', R: '#8a8578' },
      map: [
        '.....kkkkkk.....',
        '....kWWWWWWk....',
        '...kWWWWWWWWk...',
        '...kWEkWWkEWk...',
        '...kWWWWWWWWk...',
        '....kWkkkkWk....',
        '.....kwwwwk.....',
        '...kkkWWWWkkk...',
        '..kWkwWwwWwkWk..',
        '..kWkWWWWWWkWk..',
        '..kwkwWwwWwkwk..',
        '..kWk.wWWw.kWk..',
        '.......ww.......',
        '.....kwkkwk.....',
        '.....kwk.kwk....',
        '....kkk..kkk....',
      ],
    },
    ghost: {
      colors: { k: '#2a2444', A: '#d8d4f0', B: '#b0abd4', E: '#1a1626', m: '#8d88b8' },
      map: [
        '................',
        '......kkkk......',
        '....kkAAAAkk....',
        '...kAAAAAAAAk...',
        '..kAAAAAAAAAAk..',
        '..kAAEkAAkEAAk..',
        '.kAAAEkAAkEAAAk.',
        '.kAAAAAAAAAAAAk.',
        '.kAAAAkEEkAAAAk.',
        '.kAAAAAkkAAAAAk.',
        '.kABAAAAAAAABAk.',
        '.kAAAAAABAAAAAk.',
        '.kAABAAAAAABAAk.',
        '.kmAkAmBkABkAmk.',
        '..kk.kAAk.kAk...',
        '......kk...k....',
      ],
    },
    golem: {
      colors: { k: '#1f1a14', A: '#8a8578', B: '#6b665a', E: '#ffb84a', m: '#524e44', W: '#a8a494' },
      map: [
        '....kkkkkkkk....',
        '...kAAAAAAAAk...',
        '..kAWAAAAAAWAk..',
        '..kAAEkAAkEAAk..',
        '..kAAAAAAAAAAk..',
        '..kAAAkkkkAAAk..',
        '.kkAAAAAAAAAAkk.',
        'kAAkAAABBAAAkAAk',
        'kABkABAAAABAkBAk',
        'kAAkAAAmmAAAkAAk',
        'kmAkABAAAABAkAmk',
        'kkkkAAAAAAAAkkkk',
        '...kABAABAABk...',
        '...kkAAkkAAkk...',
        '..kAAAk..kAAAk..',
        '..kkkkk..kkkkk..',
      ],
    },
    mage: {
      colors: { k: '#161226', H: '#6b4fc0', h: '#523a99', A: '#3f3366', E: '#ffd94a', F: '#0e0b1c', S: '#c49658', s: '#96702e' },
      map: [
        '.......kk.......',
        '......kHHk......',
        '.....kHHHHk.....',
        '.....kHhHHk.....',
        '....kHHHHHHk....',
        '...kHHHhHHHHk...',
        '..kkkkkkkkkkkk..',
        '...kFFFFFFFFk.S.',
        '...kFEkFFkEFk.S.',
        '...kFFFFFFFFk.S.',
        '..kAAAAAAAAAAkS.',
        '..kAhAAAAAAhAkS.',
        '.kAAAAAAAAAAAkS.',
        '.kAhAAAAAAAhAkS.',
        '.kAAAAAAAAAAAkS.',
        '.kkkkkkkkkkkkkS.',
      ],
    },
    snake: {
      colors: { k: '#14240f', A: '#5aa838', B: '#437c2c', E: '#e05252', T: '#e05252', W: '#c4e0a8', Y: '#ffd94a' },
      map: [
        '.....kkkk.......',
        '....kAAAAk......',
        '...kAAAAAAk.....',
        '...kAEkAEkk.....',
        '...kAAAAAAk..T..',
        '...kAWWAAAkkT...',
        '...kAAAAAAAkT...',
        '....kAAAAAAk....',
        '.....kBAAAAk....',
        '..kkkkAAAAAk....',
        '.kAAAAAAAABk....',
        'kAABAAAAAABk....',
        'kABAAkkkAABk....',
        'kAAAAkkkAAAk....',
        '.kAAAAAAAAk.....',
        '..kkkkkkkk......',
      ],
    },

    bridge: {
      colors: { W: '#2f6fc4', r: '#5f3d1c', P: '#b0763e', p: '#8a5a2c', h: '#c98f52' },
      map: [
        'WWWWWWWWWWWWWWWW',
        'rrrrrrrrrrrrrrrr',
        'PPPpPPPPpPPPPpPP',
        'PPPpPPPPpPPPPpPP',
        'hhhphhhhphhhhphh',
        'PPPpPPPPpPPPPpPP',
        'PPPpPPPPpPPPPpPP',
        'pppppppppppppppp',
        'PPpPPPPpPPPPpPPP',
        'PPpPPPPpPPPPpPPP',
        'hhphhhhphhhhphhh',
        'PPpPPPPpPPPPpPPP',
        'PPpPPPPpPPPPpPPP',
        'rrrrrrrrrrrrrrrr',
        'WWWWWWWWWWWWWWWW',
        'WWWWWWWWWWWWWWWW',
      ],
    },

    // ===== townsfolk =====
    villager: {
      colors: { k: '#1a1626', H: '#8a5a2c', F: '#f2c9a0', A: '#5a8a4a', a: '#43683a', L: '#6b584c', B: '#3f4657' },
      map: [
        '................',
        '.....kkkkkk.....',
        '....kHHHHHHk....',
        '....kHFFFFHk....',
        '....kFkFFkFk....',
        '....kFFFFFFk....',
        '.....kFFFFk.....',
        '....kAAAAAAk....',
        '...kAAAAAAAAk...',
        '...kAFAAAAFAk...',
        '...kaAAAAAAak...',
        '....kAAAAAAk....',
        '....kaAAAAak....',
        '....kLLkkLLk....',
        '....kLLk.kLLk...',
        '...kkkk..kkkk...',
      ],
    },
    sage: {
      colors: { k: '#1a1626', G: '#8d88b8', F: '#e8c9a0', W: '#e8e4d8', R: '#6b5490', r: '#523c74', S: '#c49658' },
      map: [
        '.......kk.......',
        '......kGGk......',
        '.....kGGGGk.....',
        '....kGGGGGGk....',
        '....kFFFFFFk....',
        '....kFkFFkFk....',
        '...kWWWWWWWWk...',
        '...kWWWWWWWWkS..',
        '....kWWWWWWk.S..',
        '...kRRRWWRRRkS..',
        '...kRRRWWRRRkS..',
        '...kRrRRRRrRkS..',
        '..kRRRRRRRRRRkS.',
        '..kRrRRRRRRrRkS.',
        '..kRRRRRRRRRRkS.',
        '..kkkkkkkkkkkkS.',
      ],
    },
    kid: {
      colors: { k: '#1a1626', H: '#c45a2c', F: '#f2c9a0', A: '#c4a03c', L: '#5a6378', B: '#3f4657' },
      map: [
        '................',
        '................',
        '................',
        '................',
        '......kkkk......',
        '.....kHHHHk.....',
        '.....kFFFFk.....',
        '.....kFkkFk.....',
        '.....kFFFFk.....',
        '....kAAAAAAk....',
        '...kAFAAAAFAk...',
        '...kAAAAAAAAk...',
        '....kLLkkLLk....',
        '....kLLk.kLLk...',
        '....kBBk.kBBk...',
        '...kkkk..kkkk...',
      ],
    },
    bard: {
      colors: { k: '#1a1626', P: '#e05252', C: '#3a6b8a', F: '#f2c9a0', A: '#8a4a8a', a: '#6b3a6b', L: '#c49658', l: '#96702e' },
      map: [
        '.....P..........',
        '....kPkkkk......',
        '...kCCCCCCk.....',
        '....kFFFFFk.....',
        '....kFkFkFk.....',
        '....kFFFFFk.....',
        '...kAAAAAAAk....',
        '..kAAAAAAAAAk...',
        '..kAFAAAAAAAk...',
        '..kAAAAAAAkLLk..',
        '..kaAAAAAkLLLLk.',
        '...kAAAAAkLlLLk.',
        '...kaAAAAAkLLk..',
        '....kLLkkLLkk...',
        '....kLLk.kLLk...',
        '...kkkk..kkkk...',
      ],
    },

    // boss crown overlay (12x8), drawn on top of a boss sprite
    crown: {
      colors: { Y: '#ffd94a', y: '#d8a03c', R: '#e05252' },
      map: [
        'Y....Y.....Y',
        'YY..YYY...YY',
        'YYY.YYY..YYY',
        'YYYYYYYYYYYY',
        'yYYRYYYYRYYy',
        'yYYYYYYYYYYy',
        'yyyyyyyyyyyy',
        '............',
      ],
    },
  };

  // ---------- rendering ----------
  const cache = {};

  // Build (and cache) a canvas for a sprite at integer scale, with optional
  // palette overrides {char: hex} and horizontal mirroring.
  S.get = function (name, opts) {
    opts = opts || {};
    const scale = opts.scale || 3;
    const key = name + '|' + scale + '|' + (opts.mirror ? 'm' : '') + '|' + JSON.stringify(opts.palette || {});
    if (cache[key]) return cache[key];
    const def = S.DEFS[name];
    if (!def) throw new Error('unknown sprite: ' + name);
    const colors = Object.assign({}, def.colors, opts.palette || {});
    const h = def.map.length, w = def.map[0].length;
    const cv = document.createElement('canvas');
    cv.width = w * scale; cv.height = h * scale;
    const c = cv.getContext('2d');
    for (let y = 0; y < h; y++) {
      const row = def.map[y];
      for (let x = 0; x < w; x++) {
        const ch = row[x];
        if (ch === '.' || ch === undefined) continue;
        const col = colors[ch];
        if (!col) continue;
        const dx = opts.mirror ? (w - 1 - x) : x;
        c.fillStyle = col;
        c.fillRect(dx * scale, y * scale, scale, scale);
      }
    }
    cache[key] = cv;
    return cv;
  };

  // Validate all sprite maps (row lengths + unknown chars). Returns list of problems.
  S.validate = function () {
    const problems = [];
    for (const [name, def] of Object.entries(S.DEFS)) {
      const w = def.map[0].length;
      def.map.forEach((row, i) => {
        if (row.length !== w) problems.push(`${name} row ${i}: length ${row.length} != ${w}`);
        for (const ch of row) {
          if (ch !== '.' && !def.colors[ch]) problems.push(`${name} row ${i}: unknown char "${ch}"`);
        }
      });
    }
    return problems;
  };
})();
